-- Team rules: is_team_member(), profiles, member-level reads, team_roster.
--
-- Build it 14, part A of two (issue #75). THE DATABASE HALF ONLY. No app or UI
-- code goes with this migration, on purpose: the schema is proved on staging and
-- then in production before any screen depends on it.
--
-- docs/plan.md, feature 5: "See only the tasks of teams you belong to", and the
-- appendix row for the display name -- "a nickname, never a real or full name",
-- visible to "their team members". Until now nothing in this database could tell
-- you who else is in a team, so neither of those was expressible. This migration
-- adds the three pieces that make them expressible:
--
--   is_team_member() "does the signed-in person belong to this team?"
--   profiles         one nickname per person
--   team_roster      team name, display name, role -- for one screen to read
--
-- The function is created first because the read rule on profiles calls it, and
-- a policy cannot name a function that does not exist yet.
--
-- WHAT THIS CHANGES ABOUT WHO SEES WHAT. Two existing read rules were
-- OWNER-ONLY and are replaced below by MEMBER-LEVEL ones. Both replacements are
-- strict supersets -- every row the old rule returned, the new one returns -- so
-- nothing that used to be visible stops being visible:
--
--   teams         was: the owner reads their own teams.
--                 now: the owner AND the members read the team.
--   team_members  was: you read your own membership rows.
--                 now: you read the whole members list of any team you are in.
--
-- The old rules are dropped rather than left alongside the new ones. Two select
-- policies on one table are OR-ed together, so keeping a strictly narrower one
-- would change nothing about the answer and would add a second place to read
-- before you know what the table allows.
--
-- invitations is NOT touched. Its one policy stays owner-only, because an
-- invited person's address is never shown to the rest of the team
-- (docs/plan.md, "Email address: never shown to team members"). A member-level
-- read there would leak exactly what that decision protects.
--
-- ONE CONSEQUENCE WORTH KNOWING BEFORE THIS IS APPLIED. web/src/app/teams/page.tsx
-- lists teams with no owner filter and lets the select rule decide, and its
-- comment by the list says "Every team here is one this person owns". After this
-- migration that comment is wrong: a member now sees the teams they belong to on
-- "My teams", with an invite box next to each. invite-member still refuses
-- anybody who is not the owner (HTTP 403, proved by
-- scripts/staging/bob-invites-to-alices-team.mjs), so this is a wrong-looking
-- screen and not a hole. The screen is part B's job, and there is an issue
-- filed alongside this migration that says so.
--
-- DO NOT EDIT THIS FILE once it has been applied anywhere. A migration is
-- applied once; editing an applied one leaves the repository and every database
-- that has already run it silently disagreeing, and the edit reaches none of
-- them. To change any of this, add a new migration.
--
-- Where this migration has been applied is recorded in docs/environments.md and
-- evidence/, not here -- a status note kept in this file goes stale without
-- anyone noticing.

-- ---------------------------------------------------------------------------
-- 1. is_team_member(uuid) -- the one question every rule below asks
-- ---------------------------------------------------------------------------
--
-- "Does the person making this request belong to this team?" True for the
-- team's owner and for anybody with a team_members row for it.
--
-- WHO IS ASKING IS NEVER AN ARGUMENT. The function reads auth.uid() itself,
-- inside its own body. There is deliberately no user_id parameter: a function
-- that took one would answer questions about other people, and any caller could
-- pass any id. The only argument is which team.
--
-- security definer, so it runs as the role that owns it (postgres, which
-- applied this migration) rather than as the caller. That is what makes it
-- usable from the policies below without a loop: the rule on team_members asks
-- this function, and this function reads team_members. Reading that table as the
-- caller would re-enter the same rule. Running as the table's owner does not,
-- because row-level security is not applied to a table's owner unless the table
-- is set to force it, and nothing here does.
--
-- Running as postgres is also why every other guard on this function matters:
--
--   set search_path = ''  so no schema is searched implicitly. A function
--                         running with more rights than its caller must not
--                         resolve a name through a path somebody else can
--                         change, or it can be made to call their function
--                         instead of the one written here.
--   schema-qualified      the consequence of the line above: with an empty
--                         search path, public.teams, public.team_members and
--                         auth.uid() must each be written in full or they do
--                         not resolve at all.
--   stable                it reads tables and changes nothing, so Postgres may
--                         work it out once per query rather than once per row.
--
-- THE PARAMETER IS CALLED p_team_id, NOT team_id, and that is a correctness
-- matter rather than a style one. public.team_members has a column called
-- team_id, so "where m.team_id = team_id" would be a name that could mean
-- either the column or the parameter -- and if it resolved to the column it
-- would compare the column with itself and be true for every row, which is to
-- say this function would return true for everybody, for every team. Rather
-- than depend on how Postgres resolves that, the parameter is given a name no
-- column has, so there is nothing to resolve.
create function public.is_team_member(p_team_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.teams t
    where t.id = p_team_id
      and t.owner_id = auth.uid()
  ) or exists (
    select 1
    from public.team_members m
    where m.team_id = p_team_id
      and m.user_id = auth.uid()
  );
$$;

comment on function public.is_team_member(uuid) is
  'True if the signed-in person owns this team or has a team_members row for it. Takes the team only: who is asking comes from auth.uid() inside the body, never from an argument.';

-- WHO MAY CALL IT: authenticated, and nobody else.
--
-- Postgres grants execute on a new function to PUBLIC automatically, which here
-- means every role including anon -- and a function in the public schema is
-- published by PostgREST as an RPC endpoint, so "every role" means anybody who
-- can reach the API with the publishable key. Revoking from PUBLIC closes that
-- door before it is ever open.
--
-- Being the strongest kind of function in this database is the reason to bother.
-- A signed-out caller would learn little -- auth.uid() is null for anon, so it
-- answers false -- but this function runs as postgres and reads whole tables,
-- and the rule for that kind of function is to grant the narrowest thing that
-- works and nothing wider.
--
-- authenticated is what the policies below need: a policy's expression is
-- evaluated with the privileges of the role making the request, so without this
-- grant every rule that calls this function would fail for the app's own users.
--
-- anon is named explicitly as well. Revoking from PUBLIC already covers it, so
-- this second line removes nothing that was still there -- it is here so that a
-- later "grant ... to public" somewhere else cannot quietly hand the function
-- to signed-out callers without this line being noticed and dealt with too.
--
-- service_role is deliberately NOT granted. It does not need this function: it
-- bypasses row-level security entirely, so none of the policies below is even
-- evaluated for it. If a future server function wants to ask this question
-- directly, grant it then, in its own migration, with a reason.
revoke execute on function public.is_team_member(uuid) from public;
revoke execute on function public.is_team_member(uuid) from anon;
grant execute on function public.is_team_member(uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- 2. profiles -- one display name per person
-- ---------------------------------------------------------------------------

create table public.profiles (
  -- The primary key IS the auth user id. One row per person, no second id to
  -- keep in step, and no way to own two profiles. Deleting the account takes
  -- the row with it.
  user_id uuid primary key
    references auth.users (id) on delete cascade,

  -- docs/plan.md asks for a NICKNAME, never a real or full name: "So the
  -- organiser sees 'Carol', not an address". 40 characters is enough for a
  -- nickname and short enough that this column cannot become a notes field.
  display_name text not null,

  created_at timestamptz not null default now(),

  constraint profiles_display_name_not_blank check (btrim(display_name) <> ''),
  constraint profiles_display_name_length
    check (char_length(display_name) between 1 and 40)
);

comment on table public.profiles is
  'One nickname per person, keyed by auth user id. Readable by the person and by anyone who shares a team with them. docs/plan.md asks for a nickname, never a real or full name.';

-- No index beyond the primary key. Every rule and every join below finds a
-- profile BY user_id, which the primary key already indexes.

-- Without this line the rules below do nothing at all.
alter table public.profiles enable row level security;

-- Unlike teams, invitations and team_members, this table HAS write rules, and
-- that is a deliberate difference rather than an inconsistency. The other three
-- go through a server function holding the secret key because each has a limit
-- that needs counting other rows -- at most 3 teams, at most 20 pending
-- invitations, accepted exactly once. A display name has no such limit:
-- everything that must be true of it is true of the single row being written,
-- which is what a policy is good at. So there is no reason to hold a secret key
-- to set a nickname.

-- Who this lets in: the signed-in person, for their own row only. Who it keeps
-- out: everybody else, including a member of the same team, and anybody signed
-- out, because the rule is limited to the authenticated role. with check is the
-- only half an insert has, and it pins user_id to the caller, so a request
-- cannot create a profile for somebody else.
-- (select auth.uid()) is wrapped in a select on purpose: Postgres then works it
-- out once per query instead of once per row.
create policy "You can create your own profile"
  on public.profiles
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

-- Who this lets in: the signed-in person for their own row, and anybody who
-- shares a team with them. Who it keeps out: a stranger -- Bob gets his own row
-- and nothing else -- and anybody signed out.
--
-- The two "shares a team" branches are the two ways of being in a team, because
-- an owner has NO team_members row (docs/architecture.md: create-team writes
-- only to teams). So a person is reachable through a team they are a member of,
-- or through a team they own.
--
-- Each branch asks is_team_member() about MY side of that team and compares the
-- row's user_id for THEIR side. Note what the branches never do: they never take
-- a team id from the caller. The team comes from the row being read.
--
-- A note on reading public.team_members and public.teams from inside a policy:
-- both of those are themselves row-level-security protected, and their rules
-- (part 3) are is_team_member(team_id) and is_team_member(id) -- the same
-- condition each branch here already requires. So those rules filter out only
-- rows this expression would reject anyway, and the answer is the same whether
-- you reason with them or without them.
create policy "You can read your own profile and your team mates' profiles"
  on public.profiles
  for select
  to authenticated
  using (
    (select auth.uid()) = user_id
    or exists (
      select 1
      from public.team_members theirs
      where theirs.user_id = profiles.user_id
        and public.is_team_member(theirs.team_id)
    )
    or exists (
      select 1
      from public.teams owned
      where owned.owner_id = profiles.user_id
        and public.is_team_member(owned.id)
    )
  );

-- Who this lets in: the signed-in person, for their own row. Who it keeps out:
-- everybody else, team mates included, and anybody signed out. using decides
-- which rows may be changed; with check decides what they may be changed into.
-- Both are needed, or a row could be handed to somebody else by changing its
-- user_id.
create policy "You can change your own profile"
  on public.profiles
  for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

-- NO DELETE POLICY, and here is the justification the issue asks for.
--
-- Row-level security refuses what no policy allows, so nobody can delete a
-- profile row through the app at all. That is what we want, for two reasons:
--
--   1. There is nothing to delete it FOR. display_name is not null, so an empty
--      profile is not a state this table can hold; "remove my nickname" would
--      be a change, not a deletion, and the update rule above covers it.
--      docs/plan.md's appendix says the display name goes "with the account",
--      and that there is "no way in the app" yet.
--   2. The account deletes it. The foreign key above is on delete cascade, so
--      removing the auth user removes the profile. A row cannot outlive the
--      person it names.
--
-- If a "delete my account" feature ever arrives -- docs/plan.md calls its
-- absence a gap, on purpose -- it deletes the auth user, and this row goes with
-- it. That still needs no policy here.

-- ---------------------------------------------------------------------------
-- 3. The rules: members read their team and its members list
-- ---------------------------------------------------------------------------

-- teams: replace the owner-only read with a member-level one.
--
-- REPLACED: "Owners can read their own teams" from
-- 20260930101343_create_teams.sql, which was
-- using ((select auth.uid()) = owner_id).
--
-- WHY: is_team_member() is true for the owner as well as the members, so the
-- new rule returns every row the old one returned and some more. Keeping both
-- would add nothing -- select policies are OR-ed -- while leaving two rules to
-- read before you know what the table allows.
drop policy "Owners can read their own teams" on public.teams;

-- Who this lets in: the team's owner, and anybody with a team_members row for
-- the team. Who it keeps out: a signed-in person who is in neither position --
-- Bob gets nothing for Alice's team -- and anybody signed out, because the rule
-- is limited to the authenticated role.
create policy "Team members can read their team"
  on public.teams
  for select
  to authenticated
  using (public.is_team_member(id));

-- Still no insert, update or delete policy on teams, exactly as before. Only
-- the create-team function, which holds the secret key, can create a team,
-- because "at most 3 teams per person" needs a count of the caller's other
-- rows. See 20260930101343_create_teams.sql and docs/architecture.md.

-- team_members: replace the own-rows-only read with the team's whole list.
--
-- REPLACED: "People can read their own team membership" from
-- 20260930193813_create_invitations.sql, which was
-- using ((select auth.uid()) = user_id). Its comment said that listing who else
-- is in the team "needs its own decision, and its own policy, when a feature
-- asks for it". A feature has now asked: issue #75 rule 3, and part B's members
-- list. This is that policy.
--
-- WHY A REPLACEMENT AND NOT AN ADDITION: your own membership row for a team is
-- proof you are in that team, so is_team_member() is true for every row the old
-- rule returned. The new rule is a strict superset.
drop policy "People can read their own team membership" on public.team_members;

-- Who this lets in: the owner of the team and every member of it, for the whole
-- members list of that team. Who it keeps out: anybody not in the team -- Bob
-- cannot list Alice's team -- and anybody signed out.
--
-- What it does NOT reveal is worth saying, because this is the table that holds
-- "who belongs to which group". It returns user ids and join dates, nothing
-- else: no email addresses, which live in auth.users and are reachable by no
-- policy here, and no names unless the person has a profile row AND the reader
-- is allowed to read it by the rule in part 2.
create policy "Team members can read their team's members list"
  on public.team_members
  for select
  to authenticated
  using (public.is_team_member(team_id));

-- Who this lets in: the team's OWNER, to remove a member from their own team.
-- Who it keeps out: the members themselves, so one member cannot remove another
-- and cannot remove themselves; anybody who is not in the team at all; and
-- anybody signed out.
--
-- Why this one write may be a policy when every other write in this database
-- goes through a server function: the other writes each need a count of rows
-- other than the one being written -- at most 3 teams, at most 20 pending
-- invitations, accepted exactly once. This one needs a single fact about the row
-- being deleted, namely who owns its team, which is precisely what a policy
-- does well.
--
-- is_team_member() is deliberately NOT used here. It is true for members too,
-- and this rule must be true for the owner only, so it reads teams.owner_id
-- directly.
--
-- The owner cannot remove themselves this way, because an owner has no
-- team_members row at all -- there is nothing here to delete. Ownership lives in
-- teams.owner_id.
--
-- Nobody can leave a team of their own accord, and that is not an oversight:
-- docs/plan.md's appendix lists "Leave the team" as not built. It would be
-- another policy, and it needs deciding rather than assuming -- a member who can
-- delete their own row can also drop out of a team they were asked to join
-- without the organiser hearing about it.
create policy "Team owners can remove a member from their team"
  on public.team_members
  for delete
  to authenticated
  using (
    exists (
      select 1
      from public.teams t
      where t.id = team_members.team_id
        and t.owner_id = (select auth.uid())
    )
  );

-- Still no insert and no update policy on team_members. Only accept-invite,
-- holding the secret key, adds a membership row: it writes on behalf of somebody
-- who is not in the team yet, which no policy can authorise, and it has to claim
-- the invitation atomically. See 20260930193813_create_invitations.sql.

-- invitations is deliberately untouched by this migration. Its single policy
-- stays "Team owners can read their team's invitations". A member-level read
-- would show the rest of the team the addresses of people who have been invited
-- and have not joined -- the one thing docs/plan.md's "never shown to team
-- members" decision is about.

-- ---------------------------------------------------------------------------
-- 4. team_roster -- team name, display name, role
-- ---------------------------------------------------------------------------
--
-- One row per person per team, so a members list can be read without joining
-- three tables in the app. role is derived, not stored: owner for the team's
-- owner, member for everybody with a team_members row.
--
-- security_invoker = true IS THE WHOLE SAFETY OF THIS VIEW, and it is not the
-- default. A view normally reads its tables with the privileges of whoever owns
-- the view -- here postgres, which applied this migration and also owns teams,
-- team_members and profiles. Row-level security is not applied to a table's
-- owner, so the default would read every team in the database and hand the lot
-- to whoever selected from the view: every rule above bypassed by a
-- convenience. With security_invoker = true the tables are read as the person
-- asking, so the three rules above apply and Bob gets nothing.
--
-- It needs PostgreSQL 15 or later. Unverified -- no version has been read back
-- from either project. If a database rejects this line, that is what it means,
-- and the view must NOT be created without it.
--
-- There is no policy to write for a view: a view has none, and cannot have one.
-- What it returns is decided entirely by the policies on the three tables
-- underneath.
--
-- team_id and user_id are in the view as well as the three columns issue #75
-- names, because without team_id nothing can ask the view about ONE team --
-- which is exactly what the check script and part B's members list both do.
--
-- LEFT JOIN on profiles, not an inner join, on purpose: a person who has not set
-- a nickname yet still appears in their team's roster, with display_name null.
-- An inner join would have quietly dropped them, so a members list would have
-- shown a team as smaller than it is -- a missing person is a worse answer than
-- a missing name. Anything reading this view handles a null display_name.
--
-- No ordering here: a view that sorts itself is a view whose caller cannot.
create view public.team_roster
with (security_invoker = true)
as
  select
    t.id          as team_id,
    t.name        as team_name,
    t.owner_id    as user_id,
    p.display_name,
    'owner'::text as role
  from public.teams t
  left join public.profiles p on p.user_id = t.owner_id

  union all

  select
    t.id           as team_id,
    t.name         as team_name,
    m.user_id      as user_id,
    p.display_name,
    'member'::text as role
  from public.team_members m
  join public.teams t on t.id = m.team_id
  left join public.profiles p on p.user_id = m.user_id;

comment on view public.team_roster is
  'One row per person per team: team_id, team_name, user_id, display_name, role (owner or member). Created with security_invoker = true, so it reads its tables as the person asking and the policies on teams, team_members and profiles decide what comes back. display_name is null for somebody who has not set a nickname.';
