-- Teams: one row per team, owned by the person who created it.
--
-- docs/plan.md, feature 2: "Create a team: a name of 1 to 60 characters. One
-- person may own at most 3 teams."
--
-- THE IMPORTANT THING ABOUT THIS FILE: there is a select rule and nothing else.
-- No insert rule, no update rule, no delete rule. With row-level security on,
-- an access that matches no policy is refused -- so the app, holding only the
-- publishable key, cannot create, change or delete a team at all. Creating one
-- goes through the create-team server function, which holds the secret key and
-- can therefore check the two limits above before it writes. See
-- docs/architecture.md, "The arrows that carry a secret key".
--
-- That is deliberate, not an omission. The "at most 3 teams" limit cannot be
-- enforced by a row-level rule on an insert: the rule would have to count the
-- caller's existing teams, and a check that counts other rows is exactly the
-- kind of thing a policy is bad at and a function is good at.
--
-- APPLIED TO STAGING on 2026-09-30, by the owner from their own terminal. Not
-- applied to production: that happens when this branch is merged, through
-- .github/workflows/migrate-production.yml.
--
-- So DO NOT EDIT THIS FILE to change the teams table. A migration is applied
-- once; editing an applied one leaves the repository and the staging database
-- silently disagreeing, and the edit never reaches staging at all. To change the
-- table, add a new migration. See docs/environments.md and evidence/create-team.md.

create table public.teams (
  id uuid primary key default gen_random_uuid(),

  name text not null,

  -- Who owns the team. The create-team function sets this from the caller's
  -- verified sign-in token, never from anything in the request body, so a
  -- request cannot claim to be somebody else. Deleting the account takes their
  -- teams with it.
  owner_id uuid not null
    references auth.users (id) on delete cascade,

  created_at timestamptz not null default now(),

  -- docs/plan.md: a name of 1 to 60 characters. The function checks this too
  -- and returns a readable message; this constraint is the backstop, so the
  -- limit holds even if some future caller skips the function.
  constraint teams_name_not_blank check (btrim(name) <> ''),
  constraint teams_name_length check (char_length(name) between 1 and 60)
);

comment on table public.teams is
  'One team. owner_id is set by the create-team function from the caller''s verified sign-in token. There is no insert, update or delete policy: only that function can create a team.';

-- The select rule below reads owner_id, and the function counts by owner_id, so
-- it is worth an index.
create index teams_owner_id_idx on public.teams (owner_id);

-- Without this line the rule below does nothing at all.
alter table public.teams enable row level security;

-- One rule, for reading. Limited to the authenticated role, so a signed-out
-- caller matches nothing and sees nothing.
-- (select auth.uid()) is wrapped in a select on purpose: Postgres then works it
-- out once per query instead of once per row.
create policy "Owners can read their own teams"
  on public.teams
  for select
  to authenticated
  using ((select auth.uid()) = owner_id);

-- No insert, update or delete policy, on purpose. Row-level security refuses
-- what no policy allows, so this is the whole of the app's write access to
-- teams: none. Do not add one without changing docs/plan.md first (rule 9).
