-- Invitation status: feature 3, "Invitation status" in docs/plan.md.
--
-- "queued when the row is created, then sent or failed, with a short reason
-- code on failure; visible to the team's owner only; kept and deleted with the
-- invitation."
--
-- THIS MIGRATION IS THE DATABASE CHANGE ALONE (issue #164). It adds two columns
-- and closes them to the app. Nothing writes them yet: invite-member is not
-- touched by this change and keeps working exactly as it does today, leaving
-- every new row at the default 'queued'. The function that sets them, and the
-- screen that shows them, are the next issue.
--
-- EXPAND ONLY. Both columns have a default, so every insert the current
-- function makes -- which names team_id, email, token_hash and invited_by and
-- nothing else -- still succeeds unchanged. No existing column, constraint,
-- index or policy is altered or dropped, and the one select policy is left
-- exactly as it was.
--
-- DO NOT EDIT THIS FILE. A migration is applied once; editing an applied one
-- leaves the repository and every database that has already run it silently
-- disagreeing. To change these columns, add a new migration.
--
-- Where this migration has been applied is recorded in docs/environments.md and
-- evidence/, not here.

-- ---------------------------------------------------------------------------
-- 1. The two columns
-- ---------------------------------------------------------------------------
--
-- text with a check constraint, not a Postgres enum. Two reasons: every other
-- restricted value in this schema is a check constraint
-- (invitations_email_lowercase, invitations_token_hash_shape), and an enum's
-- values cannot be removed later without recreating the type, while a check
-- constraint is replaced by a new one in a new migration.
--
-- NOT NULL with a default on both, so there is no third state to reason about.
-- A nullable status would mean "queued, or nobody has said", and the screen in
-- the next issue would have to draw both; a nullable code would make "no code"
-- two different values, null and '', which is the kind of distinction that gets
-- one branch of an `if` wrong.
--
-- Adding a column with a default does not rewrite the table on PostgreSQL 11
-- and later -- the default is recorded in the catalogue and applied on read --
-- so this is not a long lock on a table the app reads.

alter table public.invitations
  add column status text not null default 'queued';

-- Empty string, never null, when the status is not 'failed'. The constraint
-- below is what makes that true of every row rather than only the ones a
-- function wrote.
alter table public.invitations
  add column failure_code text not null default '';

comment on column public.invitations.status is
  'queued when the row is created, then sent or failed. Read by the team''s owner through the existing owner-only select policy; no client role may set or change it.';

comment on column public.invitations.failure_code is
  'A short code from a fixed list, and empty unless status is failed. Never the email service''s own words: its reply can quote the address, the subject and the message (docs/plan.md, "Invitation status"). No client role may set or change it.';

-- ---------------------------------------------------------------------------
-- 2. Existing rows
-- ---------------------------------------------------------------------------
--
-- Every row that exists when this runs is called 'sent', decided by the owner
-- on 2026-10-06 and NOT simply assumed -- because the stricter reading of
-- issue #164 ("existing rows are sent IF a row exists only after a successful
-- send") does not hold, and the PR says so in full.
--
-- What invite-member does today, in order: it inserts the row
-- (supabase/functions/invite-member/index.ts, "Create the invitation") and only
-- then sends the email ("Send the email"). If the send fails it deletes the row
-- it just made. So a row normally survives only when an email went -- but two
-- paths leave one behind whose email never did:
--
--   * the send failed AND the cleanup delete also failed. The function detects
--     this itself and logs "the invitation could not be removed ... is
--     orphaned";
--   * the function stopped between the insert and the cleanup -- a crash, a
--     timeout, a shut-down isolate -- so nothing ran the delete at all.
--
-- NEITHER LEAVES A MARK IN THE DATA. There is no column, and no combination of
-- columns, that tells such a row from one whose email went, so no `where`
-- clause here could separate them. With exactly three values allowed, 'sent' is
-- the least wrong of them for the whole set, and the mislabelling of a rare
-- orphan is a known limitation of this backfill rather than an oversight.
--
-- Unqualified on purpose: at this point in the migration the column has just
-- been created, so every existing row holds the default 'queued' and every one
-- of them is meant.

update public.invitations set status = 'sent';

-- ---------------------------------------------------------------------------
-- 3. What the two columns may hold
-- ---------------------------------------------------------------------------
--
-- Added after the backfill, so applying this migration also proves the backfill
-- it just ran satisfies them: a constraint added to a populated table is
-- validated against every existing row, and a bad backfill would stop the
-- migration here rather than reaching staging.

alter table public.invitations
  add constraint invitations_status_allowed
  check (status in ('queued', 'sent', 'failed'));

-- THE FIXED LIST OF FAILURE CODES, and why these four.
--
-- One per branch that can fail a send in the current function, so the next
-- issue has a code for every failure its code can actually reach and never a
-- reason to invent a fifth in a hurry:
--
--   not_configured  this environment is not allowed to send, or is missing a
--                   setting. decideDelivery's two refusals.
--   unreachable     the request to the email service could not be made at all.
--                   sendEmail's catch around fetch.
--   refused         the email service answered, with a status that was not 2xx.
--                   sendEmail's `!response.ok`.
--   unconfirmed     the service answered 2xx but no email can be said to exist:
--                   the body was not JSON, or carried no id. sendEmail's last
--                   two refusals, which are one fact for somebody reading a
--                   screen -- "it answered, and we still cannot say it went".
--
-- ADDING A CODE NEEDS A NEW MIGRATION, which is the point of a fixed list: a
-- code is a word that appears on a screen, and the set of words a screen can
-- draw should change deliberately and visibly, not because a function was
-- edited. docs/plan.md: "a short reason code and nothing more -- never the
-- email service's full reply, which can quote the address, the subject and the
-- message."
--
-- Both columns are NOT NULL, so this check has no null to fall through: it
-- never evaluates to unknown, and "unknown" is how a check constraint silently
-- accepts a row it was written to refuse.
alter table public.invitations
  add constraint invitations_failure_code_allowed
  check (
    (status = 'failed'
      and failure_code in ('not_configured', 'unreachable', 'refused', 'unconfirmed'))
    or
    (status <> 'failed' and failure_code = '')
  );

-- ---------------------------------------------------------------------------
-- 4. Who may reach the two columns
-- ---------------------------------------------------------------------------
--
-- WHAT THE NEW COLUMNS GET BY DEFAULT, which is the reason this section exists
-- at all. Supabase grants select, insert, update and delete on every table in
-- the public schema to anon, authenticated and service_role -- its changelog of
-- 28 April 2026, "Breaking Change: Tables not exposed to Data and GraphQL API
-- automatically": "select, insert, update, and delete are granted to every
-- table in the `public` schema to the `anon`, `authenticated` and
-- `service_role` roles." Those are TABLE-level grants, and a table-level grant
-- covers every column the table ever grows. So without the lines below, status
-- and failure_code arrive insertable and updatable by the app's own two roles.
--
-- Row-level security refuses those writes today anyway -- invitations has one
-- policy, for select, and an access matching no policy is refused. That is a
-- second lock, not a reason to leave the first one open: privileges are checked
-- BEFORE row-level security, and the day somebody adds an insert or update
-- policy to this table for a feature that has nothing to do with status, these
-- two columns must not come with it.
--
-- WHY A COLUMN-LEVEL REVOKE WOULD NOT WORK, and this is the whole shape of what
-- follows. A table-level privilege cannot have a column carved out of it:
-- `revoke update (status) ... from authenticated` removes a column-level grant,
-- and there is none -- the reach comes from the table-level grant, which stays.
-- The only way to express "every column except these two" is to take the
-- table-level privilege away and give back a column list.
--
-- DELETE and SELECT are deliberately untouched:
--
--   * select, because the team's owner must be able to read the two columns
--     through the policy that is already there, and a table-level select
--     already covers them. anon and authenticated also keep table-level select,
--     exactly as they do today for `email` and `token_hash` -- and read nothing,
--     because the one policy matches only the team's owner and a signed-out
--     caller matches no policy at all. Narrowing select here would be a change
--     to a working read, which "expand only" forbids;
--   * delete, because nothing about a status changes who may remove an
--     invitation.

revoke insert, update on table public.invitations from anon, authenticated;

-- Given straight back, column by column, for every column that existed before
-- this migration. The reach of anon and authenticated is therefore EXACTLY what
-- it was a moment ago, minus the two new columns -- which is the whole intended
-- change and nothing besides. Both roles still have no insert or update policy,
-- so both still write nothing; this keeps the privilege layer honest about what
-- it would allow if one were ever added.
--
-- A column added to this table by a later migration will not be in these lists
-- and will therefore be closed to both roles until a migration opens it. That
-- is the safer direction to fail in, and it is said here so the next person to
-- add a column knows it is waiting for them.
grant insert (id, team_id, email, token_hash, invited_by, created_at, expires_at, accepted_at)
  on table public.invitations to anon, authenticated;

grant update (id, team_id, email, token_hash, invited_by, created_at, expires_at, accepted_at)
  on table public.invitations to anon, authenticated;

-- The server functions' role, named explicitly for the two new columns.
--
-- service_role already holds table-level insert and update here by the project
-- default above, so this grants nothing it cannot already do today. It is
-- written down because issue #164 asks that only the server function's role may
-- set these two, and a permission that rests entirely on a default nobody wrote
-- is a permission nobody can see.
--
-- IT IS ONLY THE TWO NEW COLUMNS. Everything else service_role does on this
-- table -- the insert in invite-member, the accepted_at update in
-- accept-invite, both deletes -- still rests on the project default, and this
-- migration does not change that either way.
--
-- AND THAT IS NOT A NEW EXPOSURE, which is worth saying so nobody reads this
-- grant as fixing something. Supabase applies "tables in public are not exposed
-- by default" to all existing projects on 30 October 2026, and issue #130
-- holds that whole question -- but #130's own sandbox shows the change is to
-- DEFAULT privileges, so a table that already exists keeps the grants it has:
-- "the old table keeps its grants, the new one has none". public.invitations
-- already exists. The date is a question about tables created after it, and
-- this migration creates none.
grant insert (status, failure_code), update (status, failure_code)
  on table public.invitations to service_role;
