-- Files attached to a task: the private `attachments` bucket and its rules.
--
-- docs/plan.md, "Files attached to a task", added 2026-10-08 with the owner's
-- eight decisions already in it, and docs/architecture.md, "`attachments`, its
-- rules, and how a browser gets a signed link".
--
-- THIS MIGRATION IS THE DATABASE AND STORAGE-RULE CHANGE ALONE (issue #237).
-- One bucket, four small functions, three policies on storage.objects, one
-- trigger on public.tasks, and one grant written out that today is a no-op.
-- NO SCREEN, NO EDGE FUNCTION, NO TEST AND NO WORKFLOW is touched by it.
-- Nothing in this repository can upload a file after it, and nothing can draw
-- one: the screen and the upload path are later issues. So the bucket is
-- created empty and stays empty.
--
-- EXPAND ONLY. One new bucket row, four new functions, three new policies on a
-- table that has none today, one new trigger, and one `grant select` that the
-- app already holds. No existing table, column, constraint, index, policy,
-- trigger or function is altered or dropped, and every existing rule on
-- public.tasks keeps working unchanged.
--
-- THE OWNER'S CORRECTION, 8 October 2026, which this file is written to and
-- which issue #237's own text predates. The issue says of DELETE: "only the
-- person who uploaded it, and only while they can still see the task." The
-- owner settled #234 the same day with a third answer: **a file may be deleted
-- by whoever uploaded it, OR by whoever created its task, and by nobody else --
-- in both cases only while they can still see the task.** docs/plan.md and
-- docs/architecture.md both carry that wording. Section 6.3 below is the policy,
-- and the reason the wider rule is the right one is the deadlock it removes: the
-- trigger in section 7 refuses to delete a task that still has files, so with
-- "only the uploader" a team task's creator could be left unable to delete her
-- own task because another member's photograph sat on it.
--
-- DO NOT EDIT THIS FILE once it has been applied anywhere. A migration is
-- applied once; editing an applied one leaves the repository and every database
-- that has already run it silently disagreeing, and the edit reaches none of
-- them. To change any of this, add a new migration.
--
-- Where this migration has been applied is recorded in docs/environments.md and
-- evidence/, not here -- a status note kept in this file goes stale without
-- anyone noticing. On the day it was written it had been applied NOWHERE: not
-- local, not staging, not production. Rule 19: the assistant does not run
-- `db push` anywhere, and the guard refuses every `db push` except `--local`.
--
-- ---------------------------------------------------------------------------
-- WHAT THIS FILE RESTS ON THAT IT DOES NOT WRITE, said first because it is the
-- shortest list of ways it can fail on a real project
-- ---------------------------------------------------------------------------
--
--   1. storage.objects has row-level security switched on. Supabase's own
--      documentation describes the service that way -- "By default Storage does
--      not allow any uploads to buckets without RLS policies. You selectively
--      allow certain operations by creating RLS policies on the
--      `storage.objects` table"
--      (https://supabase.com/docs/guides/storage/security/access-control, read
--      2026-10-08) -- so the three policies below are what admit anything at
--      all. This file does NOT run `alter table storage.objects enable row
--      level security`, because storage is a Supabase-managed schema and
--      switching settings on a platform table is not an expand step.
--      UNVERIFIED on either project: nobody writing this has read
--      pg_class.relrowsecurity for that table.
--
--   2. `authenticated` holds table-level SELECT, INSERT and DELETE on
--      storage.objects. Privileges are checked BEFORE row-level security, so a
--      policy cannot admit a role that has no privilege. That grant is
--      Supabase's, on a Supabase-managed table, and this file does not write it
--      for the same reason as (1). Supabase's 30 October 2026 change (changelog
--      45329) does not reach it: that change is about tables in the PUBLIC
--      schema, and storage.objects is neither new nor in public.
--
--   3. Whatever applies this migration may insert into storage.buckets and
--      create policies on storage.objects. Supabase documents both shapes --
--      `insert into storage.buckets (id, name, public) values (...)`
--      (https://supabase.com/docs/guides/storage/buckets/creating-buckets) and
--      "RLS policies on `storage.objects`, `storage.buckets`" as customizations
--      to "manage ... through versioned migrations"
--      (https://supabase.com/docs/guides/local-development/declarative-database-schemas),
--      both read 2026-10-08. Neither page names the role. UNVERIFIED, and it is
--      the most likely way this file fails on staging: if it does, it fails
--      LOUDLY, on the first statement, having changed nothing. Issue #239 holds
--      all three of these, with the queries that settle them.
--
--   4. public.is_active() is executable by `authenticated`.
--      20261004114313_suspend_accounts.sql grants that by name, so this one
--      rests on something written down rather than on a default.

-- ---------------------------------------------------------------------------
-- 1. The bucket
-- ---------------------------------------------------------------------------
--
-- PRIVATE, which is the first line of the design rather than a setting.
-- `public => false` means there is no address that works: nothing in this
-- bucket can be fetched by URL, and the only route to a file's bytes is a
-- signed link the app asks for on behalf of somebody the SELECT policy below
-- has already admitted. A public bucket would make every rule in this file
-- decoration.
--
-- TWO RESTRICTIONS LIVE ON THE BUCKET ITSELF, so they hold whoever is uploading
-- and whatever screen they came from. Supabase: "If an upload request doesn't
-- meet the above restrictions it will be rejected"
-- (https://supabase.com/docs/guides/storage/buckets/creating-buckets, read
-- 2026-10-08), and the refusal is `InvalidMimeType`, "The specified MIME type is
-- not valid.", 400
-- (https://supabase.com/docs/guides/storage/debugging/error-codes, read
-- 2026-10-08).
--
-- 5 MB IS 5 * 1024 * 1024 = 5242880 BYTES, and the unit is a decision rather
-- than an obvious reading. docs/plan.md's own arithmetic forces it: it says
-- 100 MB is "20 single 5 MB files", which is only true if both numbers use the
-- same unit, and section 5 below uses 100 * 1024 * 1024 for the same reason.
-- 5 MB also sits well under what Supabase would allow -- "For Free projects,
-- the limit can't exceed 50 MB", and a bucket's own limit "can't be higher than
-- this global limit"
-- (https://supabase.com/docs/guides/storage/uploads/file-limits, read
-- 2026-10-08).
--
-- 'image/*' IS A WILDCARD, AND THAT IT WORKS IN THIS COLUMN IS AN INFERENCE
-- rather than a citation. Supabase's documented JavaScript form is
-- `allowedMimeTypes: ['image/*']` (the creating-buckets page above), and the
-- schema page lists `allowed_mime_types` as a column of storage.buckets
-- (https://supabase.com/docs/guides/storage/schema/design, read 2026-10-08).
-- That the column takes the same wildcard spelling as the option is read off the
-- two pages together, and no page read says it. If it turns out not to, every
-- image upload is refused -- a loud, visible failure, not a quiet hole -- and
-- the fix is one migration listing the types in full. Settling it needs one
-- upload of each kind to staging.
--
-- AND WHAT THE TYPE LIMIT DOES NOT PROMISE, which docs/plan.md puts in the plan
-- rather than leaving to be inferred: "By default, Supabase Storage determines
-- content type from the file extension. You can override this with the
-- `contentType` option"
-- (https://supabase.com/docs/guides/storage/uploads/standard-uploads, read
-- 2026-10-08). Both halves of that are chosen by whoever is uploading, so A
-- RENAMED FILE GETS THROUGH. The bucket enforces the refusal, never the
-- contents. The owner accepted that as written on 2026-10-08.
--
-- NO `on conflict`, on purpose. A migration is applied once, and a bucket that
-- already exists with other settings is something a person should look at rather
-- than something this statement should quietly skip.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'attachments',
  'attachments',
  false,
  5242880,
  array['image/*', 'application/pdf']
);

-- ---------------------------------------------------------------------------
-- 2. attachments_task_id() -- the whole of "which task is this file on?"
-- ---------------------------------------------------------------------------
--
-- A file lives at `attachments/<task id>/<file name>`, so the first segment of
-- the object's name is the task's ID. storage.objects.name holds the path
-- WITHOUT the bucket, which is what Supabase's own example says: a file stored
-- in `public/subfolder/avatar.png` gives `storage.foldername(name)` of
-- `[ 'public', 'subfolder' ]`
-- (https://supabase.com/docs/guides/storage/schema/helper-functions, read
-- 2026-10-08). So for this project a well-formed name has exactly two segments.
--
-- THIS FUNCTION IS THE ONE PLACE THAT DECIDES WHAT WELL-FORMED MEANS, and every
-- policy below asks it rather than re-deriving it. It returns the task's id, or
-- NULL -- and NULL is how "nothing at the bucket's top level", "nothing nested
-- deeper" and "that is not a task id" all come out as the same answer.
--
-- WHY IT IS NOT storage.foldername(), which is the Supabase-blessed idiom and is
-- cited above. Three reasons, and the third is the one that decided it:
--
--   * the page documents what it returns for a nested path and says nothing
--     about a file at the top level, which is exactly one of the two cases this
--     project has to be exact about;
--   * `(storage.foldername(name))[1]` is 'a' for both `a/f.png` and
--     `a/b/f.png`, so a length check is needed beside it either way;
--   * and a local sandbox cannot contain storage.foldername. Standing in for it
--     would mean proving this project's rules against the assistant's guess at
--     somebody else's function. `string_to_array(name, '/')` is plain
--     PostgreSQL, it cannot change under us, and the proof in
--     evidence/build-it-23-attachments-bucket.md is therefore about the
--     expression this file actually ships.
--
-- IT NEVER CASTS A CALLER'S TEXT TO uuid WITHOUT LOOKING FIRST. A bare
-- `'not-a-uuid'::uuid` raises, and an error is a different answer from a
-- refusal: it would tell whoever is probing that their path was malformed
-- rather than unknown, and an error raised inside a policy aborts the statement
-- instead of hiding the row. The regexp is checked first, so a path that is not
-- a uuid is simply NULL and is refused exactly like a task that does not exist.
--
-- lower() IS DELIBERATE. uuid::text is lowercase and hyphenated, so a path
-- carrying the same id in capitals would otherwise match nothing and the file
-- would be invisible to its own task. Accepting either spelling costs nothing:
-- there is no privilege in a spelling, and section 5's count reads this same
-- function, so two spellings of one task still share one allowance of three.
--
-- NOT security definer: it reads no table and asks no question about anybody,
-- so it needs no privilege of its own. immutable, so Postgres may work it out
-- once per value. `set search_path = ''` for the house reason -- everything it
-- calls is in pg_catalog, which is searched whatever the path says.
create function public.attachments_task_id(p_name text)
returns uuid
language sql
immutable
set search_path = ''
as $$
  select case
    when p_name is null then null
    -- Exactly two segments: one folder, one file name. One segment is a file at
    -- the bucket's top level; three or more is a folder inside the task's
    -- folder; `a//b.png` is three segments with an empty one and goes the same
    -- way.
    when array_length(string_to_array(p_name, '/'), 1) is distinct from 2 then null
    -- A name that is empty or only spaces. The first segment cannot be empty
    -- and still match the regexp below, so only the second needs saying.
    when btrim((string_to_array(p_name, '/'))[2]) = '' then null
    when lower((string_to_array(p_name, '/'))[1]) !~
      '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' then null
    else lower((string_to_array(p_name, '/'))[1])::uuid
  end;
$$;

comment on function public.attachments_task_id(text) is
  'The id of the task a stored object belongs to, read off the first segment of its storage.objects.name, or NULL if the name is not exactly <task id>/<file name> with a well-formed id. NULL is the one answer for a file at the bucket''s top level, a file nested deeper, and a first segment that is not a uuid -- so all three are refused the way a task that does not exist is refused. Never casts unchecked text to uuid, because an error is not a refusal.';

-- WHO MAY CALL IT: authenticated, because the three policies below call it and a
-- policy's expression is evaluated with the privileges of the role making the
-- request. Without this grant every rule below would fail with 42501 for the
-- app's own users.
--
-- It discloses nothing: it is string handling over a value the caller already
-- holds, and it reads no table.
--
-- PUBLIC and anon are revoked by name for the reason
-- 20261004114313_suspend_accounts.sql gives in full: Postgres grants EXECUTE on
-- a new function to PUBLIC, and Supabase grants it to anon, authenticated and
-- service_role BY NAME as well, which are different grants that a revoke from
-- PUBLIC does not remove. service_role's grant therefore survives these lines
-- and is left alone -- it bypasses row-level security, so being able to ask this
-- question tells it nothing it could not work out.
revoke execute on function public.attachments_task_id(text) from public;
revoke execute on function public.attachments_task_id(text) from anon;
grant execute on function public.attachments_task_id(text) to authenticated;

-- ---------------------------------------------------------------------------
-- 3. attachments_file_bytes() -- one definition of "fail closed on an unknown
--    size"
-- ---------------------------------------------------------------------------
--
-- Supabase keeps a stored object's size inside storage.objects.metadata, as
-- `"metadata": {"size": 1234}`
-- (https://supabase.com/docs/reference/self-hosting-storage/get-object-info,
-- read 2026-10-08). The 100 MB in section 5 is a sum of those numbers, so this
-- function is what the sum is made of.
--
-- AN UNKNOWN SIZE COUNTS AS THE BIGGEST A FILE CAN BE, which is the whole point
-- of having it. A missing or unparseable size must not count as zero: that is
-- the direction in which a person's total could quietly pass 100 MB, and this
-- project has written the same sentence before -- invite-member's "an unknown is
-- not a zero" about its counts. 5242880 is the bucket's own per-file ceiling
-- from section 1, so the stand-in cannot be smaller than the file it stands in
-- for.
--
-- WHEN IT MATTERS, stated rather than discovered. It is NOT CONFIRMED whether
-- metadata is already populated at the moment a policy's `with check` is
-- evaluated for a new row -- no page read on 2026-10-08 says, and nobody has
-- tried it on Supabase. So the new file's size may be unknown to section 5, and
-- then it is treated as 5 MB. The cost of that is precise: somebody whose
-- stored files already come to more than 95 MB may be refused a small file. The
-- benefit is that the 100 MB is a ceiling that cannot be stepped over rather
-- than one that can be, and 5 MB of a 100 MB allowance is the price.
--
-- The regexp is what keeps this total: `'12'::bigint` is 12, but
-- `'1e6'::bigint` and `' 12 '::bigint` and `'99999999999999999999'::bigint` are
-- an error, a success and an error respectively, and an error raised inside a
-- policy aborts the statement. Only a plain run of digits is cast, and the
-- length cap keeps that run inside bigint.
create function public.attachments_file_bytes(p_size text)
returns bigint
language sql
immutable
set search_path = ''
as $$
  select case
    when p_size ~ '^[0-9]{1,18}$' then p_size::bigint
    else 5242880
  end;
$$;

comment on function public.attachments_file_bytes(text) is
  'How many bytes to count for a stored object, given storage.objects.metadata ->> ''size''. A plain run of up to 18 digits is that number; anything else -- absent, null, empty, not a number, too long for bigint -- counts as 5242880, the bucket''s per-file ceiling. An unknown size is never a zero, because a zero is the direction in which somebody''s total could pass 100 MB unnoticed.';

-- Needed by `authenticated` for the same reason as section 2: the INSERT policy
-- names it, by way of section 5, and policy expressions run with the caller's
-- privileges. (Section 5 is `security definer` and runs as its owner, so the
-- grant is strictly only needed if this is ever named in a policy directly; it
-- is written so that a later policy which does name it is not broken by a
-- missing grant nobody can see.)
revoke execute on function public.attachments_file_bytes(text) from public;
revoke execute on function public.attachments_file_bytes(text) from anon;
grant execute on function public.attachments_file_bytes(text) to authenticated;

-- ---------------------------------------------------------------------------
-- 4. attachments_lock_key() -- a stable bigint for an advisory lock
-- ---------------------------------------------------------------------------
--
-- Section 5 has to stop two uploads arriving at the same moment from both
-- passing a limit that has room for one, and the way it does that is a
-- transaction-scoped advisory lock. An advisory lock is taken on a number, and
-- the things being locked here are a task id and a person id, so there has to be
-- a function from one of those to a bigint.
--
-- md5 gives 32 hex characters; the first 16 are 64 bits; `('x' || ...)::bit(64)`
-- reads them as a bit string and the cast to bigint gives a number, which may be
-- negative and that is fine -- an advisory lock key is just a number.
--
-- THE 'x' PREFIX IS CONFIRMED BY A RUN, NOT BY A PAGE. PostgreSQL's
-- documentation of the bit-string types describes the `B'1010'` and `X'1FF'`
-- literal forms; this is a cast of ordinary text, which those pages do not
-- describe. evidence/build-it-23-attachments-bucket.md shows it evaluated on
-- PostgreSQL 17 with its output, which is why it is written here rather than
-- remembered. If a future PostgreSQL stops accepting it, this migration's
-- functions stop working LOUDLY -- the cast raises -- and no upload is quietly
-- let through.
--
-- THE NAMESPACE ARGUMENT IS NOT DECORATION. Two different kinds of thing are
-- locked, and the same uuid could in principle be both; prefixing the kind keeps
-- the two sets of keys apart, so a lock on a task cannot collide with a lock on
-- a person.
--
-- A HASH COLLISION IS POSSIBLE AND IS HARMLESS HERE. Two different ids could
-- share a key, and the only consequence is that two uploads that need not have
-- waited for each other do. It cannot let an upload through that should have
-- been refused, which is the only direction that would matter.
create function public.attachments_lock_key(p_kind text, p_id uuid)
returns bigint
language sql
immutable
set search_path = ''
as $$
  select (('x' || substr(md5(p_kind || ':' || p_id::text), 1, 16))::bit(64))::bigint;
$$;

comment on function public.attachments_lock_key(text, uuid) is
  'A stable bigint for pg_advisory_xact_lock, from a kind ("task" or "uploader") and an id. Only public.attachments_may_add() uses it, and only to make two simultaneous uploads take turns. A collision would make two uploads wait on each other needlessly and cannot let one through that should have been refused.';

-- NOBODY OUTSIDE THE DATABASE MAY CALL IT, including authenticated. It is only
-- ever called from inside public.attachments_may_add(), which is `security
-- definer` and therefore runs as this function's owner -- so the app needs no
-- grant here at all. Anything that could call it could take out locks in the
-- database's advisory lock space, which is a thing no browser should be able to
-- do, and the narrowest grant that works is none.
revoke execute on function public.attachments_lock_key(text, uuid) from public;
revoke execute on function public.attachments_lock_key(text, uuid) from anon;
revoke execute on function public.attachments_lock_key(text, uuid) from authenticated;
revoke execute on function public.attachments_lock_key(text, uuid) from service_role;

-- ---------------------------------------------------------------------------
-- 5. attachments_may_add() -- the two counted limits, in the database
-- ---------------------------------------------------------------------------
--
-- "At most 3 files per task and 100 MB per uploader, refused by the database at
-- upload, not only by the screen." (issue #237)
--
-- AND THIS IS A REFINEMENT OF docs/architecture.md, which this pull request
-- changes. That file says: "A row-level rule on `storage.objects` can say 'this
-- file belongs to a task you may see'; it cannot say 'and you are under your
-- 100 MB'", and it concludes that the count must live in server code. The first
-- half is true of a policy expression evaluated AS THE CALLER, which is what
-- that sentence was about: the caller cannot see every object they own, because
-- the SELECT policy below shows them files on tasks they can see and a task can
-- move out from under them. It is NOT true of a `security definer` function,
-- which is how `is_active()` already reads a table the app has no privilege on
-- at all.
--
-- SO THE DATABASE CAN COUNT, and this function is the count. What that does NOT
-- do is make the owner's decision of 2026-10-08 unnecessary, and the reason is
-- the one sharp edge of the whole design:
--
--   ROW-LEVEL SECURITY DOES NOT APPLY TO service_role. "Service keys entirely
--   bypass RLS policies, granting unrestricted access"
--   (https://supabase.com/docs/guides/storage/security/access-control, read
--   2026-10-08). docs/architecture.md offers two shapes for how the bytes
--   travel, and one of them is "the browser posts the file to a server function,
--   which ... writes it to Storage with the service-role key". IN THAT SHAPE
--   THIS FUNCTION IS NEVER CALLED, because no policy on storage.objects is
--   evaluated at all.
--
-- So: this function is the control for any upload made as `authenticated`, and
-- it is not a control at all for an upload made with the service-role key. The
-- server-side count the owner asked for is still required, and it is still
-- Build it 23's later part -- issue #240, which also carries the second half of
-- the same problem: an object uploaded with that key has no owner_id at all, so
-- it belongs to nobody's 100 MB and nobody but the task's creator can delete it.
-- What this file buys is that the numbers are also in the one place a screen
-- cannot bypass and a later code change cannot forget -- which is the same
-- argument this project makes about feature 5 living in the database rather than
-- in a page.
--
-- WHAT IT ASKS, in order, and it answers false at the first no:
--
--   1. is anybody signed in? An admin connection has no auth.uid(), and the
--      answer there is no rather than yes -- fail closed, the direction
--      20261004114313_suspend_accounts.sql spells out at length.
--   2. is the name well formed? Section 2 answers.
--   3. take the two locks, so a simultaneous upload waits rather than racing.
--   4. does this task already have 3 files?
--   5. would this file put this uploader over 100 MB?
--
-- IT DELIBERATELY DOES NOT ASK WHETHER THE CALLER MAY SEE THE TASK. That
-- question has exactly one definition in this project -- the policies on
-- public.tasks -- and it has to be asked AS THE CALLER to get that definition.
-- This function runs as its owner, so it is the wrong place to ask it; the
-- INSERT policy in section 6 asks it, beside this call. Asking it here as well,
-- as the owner, would be a second definition that could drift from the first.
--
-- WHAT A SIGNED-IN PERSON LEARNS BY CALLING IT DIRECTLY, stated because
-- `authenticated` must hold EXECUTE for the policy to work and so this is
-- reachable: one bit, about a task id they must already know, saying whether
-- that task has room for another file -- and one bit about their own stored
-- total. It cannot be asked about somebody else's total, because the uploader is
-- read from auth.uid() inside the body and is not an argument, which is the same
-- shape as is_active() and my_ai_suggestions(). A task id is a uuid, so there is
-- nothing to enumerate.
--
-- security definer, because the sums are over rows the caller cannot see -- both
-- the other files on a shared task and their own files on tasks that have since
-- moved away from them. Running as the owner is why the two house guards matter:
--
--   set search_path = ''  so no schema is searched implicitly. A function
--                         running with more rights than its caller must not
--                         resolve a name through a path somebody else can
--                         change.
--   schema-qualified      the consequence: storage.objects, public.* and
--                         auth.uid() are each written in full.
--
-- NOT stable: it takes locks, so it has an effect beyond its answer, and the
-- default volatile is both correct and the thing that makes the lock work --
-- a volatile function's statements take a fresh snapshot, so the count after
-- the lock is released sees what the upload that held it committed.
create function public.attachments_may_add(p_name text, p_size text)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  -- Three files per task. docs/plan.md, confirmed by the owner on 2026-10-08:
  -- "Three is enough for the job this app exists for -- a photo of the thing, a
  -- photo of the receipt, the form as a PDF -- and it keeps a single task's
  -- worst case at 15 MB".
  c_files_per_task constant integer := 3;

  -- 100 MB per uploader, as 100 * 1024 * 1024. Section 1 says why the unit is
  -- MiB and not a million: docs/plan.md's own "20 single 5 MB files" only adds
  -- up if both numbers use one unit.
  c_bytes_per_uploader constant bigint := 104857600;

  l_uploader uuid := auth.uid();
  l_task_id uuid;
  l_files integer;
  l_bytes bigint;
begin
  -- Nobody signed in: no. This is reached by service_role only if something
  -- calls the function deliberately -- policies are never evaluated for it --
  -- and "no" is the answer that cannot let a file through uncounted.
  if l_uploader is null then
    return false;
  end if;

  l_task_id := public.attachments_task_id(p_name);

  if l_task_id is null then
    return false;
  end if;

  -- -----------------------------------------------------------------
  -- TWO UPLOADS AT THE SAME MOMENT
  -- -----------------------------------------------------------------
  --
  -- A count in a `with check` is a read followed by a write, which is the exact
  -- shape 20261008115900_usage_counts.sql exists to avoid: two uploads that both
  -- read "2 files" both pass, and the task ends with 4. There is no
  -- single-statement trick available here, because the two uploads are inserting
  -- DIFFERENT rows and so have no key to conflict on.
  --
  -- So they are made to take turns. pg_advisory_xact_lock blocks until the lock
  -- is free and holds it until the transaction ends, so the second upload waits
  -- for the first to commit or roll back and then counts what the first actually
  -- left behind. The count below runs inside a volatile function, which takes a
  -- fresh snapshot per statement, so it sees the committed row rather than the
  -- snapshot the second upload's statement started with.
  --
  -- MEASURED, NOT ARGUED: evidence/build-it-23-attachments-bucket.md races
  -- twenty simultaneous inserts at a limit of three, with and without these two
  -- lines, and reports what each run let through.
  --
  -- ALWAYS THE SAME ORDER, task before uploader, which is what keeps two
  -- uploads from deadlocking on each other. Two transactions that take the same
  -- two kinds of lock in the same order cannot each be holding what the other
  -- wants.
  --
  -- WHAT THIS STILL DOES NOT COVER is named in the pull request: it serialises
  -- callers that go through this function, and nothing goes through it when the
  -- service-role key is used.
  perform pg_advisory_xact_lock(public.attachments_lock_key('task', l_task_id));
  perform pg_advisory_xact_lock(public.attachments_lock_key('uploader', l_uploader));

  -- -----------------------------------------------------------------
  -- 3 files per task
  -- -----------------------------------------------------------------
  --
  -- `o.name <> p_name` IS WHAT MAKES THIS COUNT RIGHT WHETHER OR NOT THE NEW ROW
  -- IS ALREADY VISIBLE. Whether a `with check` expression can see the row being
  -- inserted is an implementation detail nobody writing this has found written
  -- down, and the two readings differ by one -- which is the difference between
  -- a limit of 3 and a limit of 2. Excluding the exact name being written is
  -- correct either way: if the row is invisible the clause removes nothing, and
  -- if it is visible it removes exactly it. A name is unique within a bucket --
  -- an upload to an existing path answers "400 Asset Already Exists" unless
  -- upsert is asked for
  -- (https://supabase.com/docs/guides/storage/uploads/standard-uploads, read
  -- 2026-10-08) -- and no policy here permits upsert, so the clause can never
  -- exclude somebody else's file.
  select count(*)
    into l_files
  from storage.objects o
  where o.bucket_id = 'attachments'
    and o.name <> p_name
    and public.attachments_task_id(o.name) = l_task_id;

  if l_files + 1 > c_files_per_task then
    return false;
  end if;

  -- -----------------------------------------------------------------
  -- 100 MB per uploader
  -- -----------------------------------------------------------------
  --
  -- owner_id IS COMPARED AS TEXT ON BOTH SIDES, deliberately. Supabase's
  -- ownership page gives the policy example `owner_id = (select
  -- auth.uid()::text)`
  -- (https://supabase.com/docs/guides/storage/security/ownership, read
  -- 2026-10-08), which reads as though the column is text, and no page read
  -- states its type. Casting both sides to text is the comparison that is
  -- correct whichever it is. The cost is that no index on owner_id can serve it,
  -- which for a group of about six people holding at most 100 MB each is a scan
  -- of a few hundred rows at worst.
  --
  -- AND THE ONE THING THIS SUM CANNOT SEE: an object uploaded with the
  -- service-role key has NO owner. "When using the `service_key` to create a
  -- resource, the owner will not be set and the resource will be owned by anyone"
  -- (the ownership page above). Such a file belongs to nobody's total, so it is
  -- not counted against anybody -- which is the second reason the pull request
  -- argues for uploading as the signed-in person rather than through a key.
  select coalesce(sum(public.attachments_file_bytes(o.metadata ->> 'size')), 0)
    into l_bytes
  from storage.objects o
  where o.bucket_id = 'attachments'
    and o.name <> p_name
    and o.owner_id::text = l_uploader::text;

  if l_bytes + public.attachments_file_bytes(p_size) > c_bytes_per_uploader then
    return false;
  end if;

  return true;
end;
$$;

comment on function public.attachments_may_add(text, text) is
  'Whether the signed-in person may add one more file at this path: true when the task has fewer than 3 files and the person''s stored attachments plus this one come to no more than 100 MB. Who is asking is read from auth.uid() inside the body and is never an argument, so it cannot be asked about anybody else. It does NOT ask whether the caller may see the task -- the INSERT policy asks that, as the caller, so there stays one definition of it. Takes two transaction advisory locks so that two uploads at the same moment take turns instead of both passing a limit with room for one. security definer, because the two sums are over rows the caller cannot see. It is not evaluated at all for a caller using the service-role key, which bypasses row-level security.';

-- Needed by `authenticated`, because the INSERT policy below names it and a
-- policy's expression is evaluated with the privileges of the role making the
-- request. The paragraph above the function says what a direct call discloses:
-- one bit about a task id the caller already holds, and one bit about their own
-- total.
revoke execute on function public.attachments_may_add(text, text) from public;
revoke execute on function public.attachments_may_add(text, text) from anon;
grant execute on function public.attachments_may_add(text, text) to authenticated;

-- ---------------------------------------------------------------------------
-- 6. The rules on storage.objects
-- ---------------------------------------------------------------------------
--
-- THREE POLICIES, AND THE FOURTH IS AN ABSENCE. Each one is a sentence in
-- English before it is SQL, and the sentences are in the pull request too:
--
--   SELECT  You can see, list and get a link for a file if you can see the task
--           it is on, and you are not suspended.
--   INSERT  You can attach a file to a task you can see, if you are not
--           suspended, the row does not name somebody else as its uploader, the
--           task has fewer than three files, and your own files come to under
--           100 MB.
--   DELETE  You can delete a file if you can still see its task, you are not
--           suspended, and either you uploaded it or you created the task.
--           (Its policy is NAMED more briefly than that, because a policy name
--           is an identifier and is cut at 63 bytes -- see 6.3.)
--   UPDATE  Nobody. There is no policy, so nothing can be replaced or renamed.
--
-- WHAT EVERY ONE OF THEM HAS IN COMMON, and it is the design rather than
-- repetition:
--
--   bucket_id = 'attachments'   so these rules say nothing about any other
--                               bucket. A permissive policy can only add
--                               access, and these add none outside this bucket:
--                               there is no other bucket today, and if one
--                               arrives it is as closed as it would have been.
--
--   to authenticated            so a signed-out caller matches no policy on
--                               this table and gets nothing. anon is not named
--                               in a condition anywhere, because naming it
--                               would add a condition to a door that is already
--                               shut.
--
--   (select public.is_active()) so a suspended person is refused all three.
--                               docs/architecture.md: it is not inherited from
--                               the subquery on public.tasks even though that
--                               subquery already refuses them -- writing it
--                               costs nothing and means the storage rule still
--                               refuses if anything about that chain changes.
--                               Wrapped in a select so Postgres works it out
--                               once per query rather than once per row, as
--                               every rule in this schema wraps
--                               (select auth.uid()).
--
--   exists (select 1 from public.tasks t where t.id = ...)
--                               THE WHOLE OF "the same rules as tasks". This
--                               subquery runs AS THE CALLER, so the policies on
--                               public.tasks filter it -- their own personal
--                               task, or a task of a team they belong to, and
--                               nothing else. So this file does not restate
--                               feature 5, it ASKS it, and cannot drift from
--                               it. There is exactly one definition of "may
--                               this person see this task" in this project and
--                               attachments must not become a second.
--
--   attachments_task_id(...) is not null
--                               not strictly needed beside the exists() -- a
--                               null id matches no task -- and written anyway,
--                               because "nothing at the top level" is a rule
--                               somebody should be able to read off the policy
--                               rather than deduce from what a join does with a
--                               null.
--
-- AND WHAT A PATH WITH A MADE-UP TASK ID GETS: nothing, by the same sentence
-- that refuses a path with no folder and a path nested two deep. The exists()
-- finds no row, so there is no row to return and no error to read -- which is
-- the issue's "refused exactly like a task that does not exist", and it is the
-- same answer a caller gets for a task that exists and is somebody else's.

-- 6.1 SELECT -- see that a file is there, list a task's files, and get a link.
--
-- Supabase's access-control page is explicit that creating a signed URL is a
-- read: this is the policy that decides whether a browser gets a link at all,
-- and the check happens WHEN THE LINK IS MADE AND NEVER AGAIN -- for the five
-- minutes a link lives, whoever holds it can open the file. docs/plan.md,
-- "Links, and what an unexpired one allows", is where that is written up; it is
-- a property of signed links and not something this policy can reach.
--
-- LISTING IS A SELECT TOO, and how much of it goes through this policy is NOT
-- CONFIRMED. The page distinguishes "listing objects versus reading
-- authenticated objects" and offers no more than that, and nobody has tried it.
create policy "Attachments: read a file on a task you can see"
  on storage.objects
  for select
  to authenticated
  using (
    bucket_id = 'attachments'
    and (select public.is_active())
    and public.attachments_task_id(objects.name) is not null
    and exists (
      select 1
      from public.tasks t
      where t.id = public.attachments_task_id(objects.name)
    )
  );

-- 6.2 INSERT -- attach a file.
--
-- "the only RLS policy required for uploading objects is to grant the `INSERT`
-- permission to the `storage.objects` table"
-- (https://supabase.com/docs/guides/storage/security/access-control, read
-- 2026-10-08). So this policy is the whole of what admits an upload made as the
-- signed-in person -- and nothing of what admits one made with the service-role
-- key, which is section 5's sharp edge.
--
-- `with check` is the only half an insert has. The limits are called LAST, after
-- the free checks, because the limit function takes locks and does two counts
-- and there is no reason to do any of that for a path that was never going to be
-- allowed.
--
-- AND A ROW MAY NOT NAME SOMEBODY ELSE AS ITS UPLOADER, which is the fourth
-- condition and the one with a deliberate hole in it. Every insert policy in
-- this project pins the row's owner to the caller -- "a request cannot create a
-- task for someone else" -- and the same reasoning applies here twice over,
-- because owner_id is what the DELETE policy reads to decide who may remove the
-- file, and what section 5 reads to decide whose 100 MB it comes out of. So a
-- row claiming a different person's id would hand them a deletion right and
-- spend their allowance.
--
-- `objects.owner_id is null or ...` is the hole, and it is there rather than
-- absent because of something NOT CONFIRMED. Supabase says an owner "is
-- automatically assigned" when an object is created and is "derived from the
-- `sub` claim in the JWT"
-- (https://supabase.com/docs/guides/storage/security/ownership, read
-- 2026-10-08), but no page read says the column is already filled at the moment
-- this expression runs. A strict pin would, if it is not, refuse every single
-- upload -- so this condition refuses the thing somebody could gain by
-- (claiming another person) and permits the thing that may simply be how
-- Storage works (not set yet).
--
-- WHAT THE HOLE COSTS: a row written with no owner belongs to nobody's 100 MB.
-- The same is true of an upload made with the service-role key, where the
-- ownership page says outright that "the owner will not be set" -- so this is
-- the second of two reasons the pull request argues for uploading as the
-- signed-in person. Neither is reachable through the Storage API, which is the
-- only way into this bucket: a browser cannot choose an owner.
create policy "Attachments: attach a file to a task you can see"
  on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'attachments'
    and (select public.is_active())
    and public.attachments_task_id(objects.name) is not null
    and exists (
      select 1
      from public.tasks t
      where t.id = public.attachments_task_id(objects.name)
    )
    and (
      objects.owner_id is null
      or objects.owner_id::text = (select auth.uid())::text
    )
    and public.attachments_may_add(objects.name, objects.metadata ->> 'size')
  );

-- 6.3 DELETE -- remove a file.
--
-- THE OWNER'S DECISION OF 2026-10-08, and the one policy here with a condition
-- about the file itself rather than only about its task: "a file may be deleted
-- by its uploader, or by the person who created its task, and by nobody else --
-- in both cases only while they can still see the task."
--
-- THREE THINGS IT GETS RIGHT, from docs/plan.md:
--
--   * the deadlock is gone. Section 7 refuses to delete a task that still has
--     files, and with "only the uploader" a team task's creator could be left
--     unable to delete her own task because somebody else's photograph was on
--     it. She can now clear it, so deleting her own task is something she can
--     simply do, and no code path needs authority the person does not have.
--   * it gives the task's creator almost nothing new. She could already destroy
--     that file by deleting the whole task, which feature 4 has always let her
--     do; what she gains is the finer version of a power she had.
--   * it keeps the protection "only the uploader" was proposed for. The person
--     that protects against is a team mate at large -- Carol, who is in the
--     team, can see the task, and neither created it nor uploaded the file.
--     CAROL STILL CANNOT DELETE ANYTHING, and "anyone who can see the task"
--     would have let her.
--
-- "ONLY WHILE THEY CAN STILL SEE THE TASK" IS THE FIRST exists(), and it bites
-- on the uploader rather than on the creator: a task's creator can always see
-- their own task, so for them it is automatically true, while an uploader whose
-- team no longer holds the task -- it was moved out, or they were removed from
-- the team -- loses the right to delete the file they attached. From then on the
-- task's creator is the only person who can.
--
-- THE TWO HALVES ARE SEPARATE SUBQUERIES on purpose. Both public.tasks and
-- storage.objects have a column called owner_id, so folding the uploader test
-- inside the subquery would put an unqualified name there that means one thing
-- in the inner scope and another in the outer. Written apart, each is
-- unambiguous and each reads as the sentence it is.
--
-- owner_id is compared as text on both sides, for the reason section 5 gives:
-- Supabase's own example casts auth.uid() to text to compare with it, no page
-- read states the column's type, and a cast on both sides is right either way.
--
-- THE NAME IS SHORTER THAN THE SENTENCE, and that is not tidiness. A policy name
-- is a PostgreSQL identifier, so it is cut at 63 bytes -- with a NOTICE, which a
-- migration run with -q does not show. The first version of this policy was
-- called "Attachments: delete a file you attached, or one on a task you created"
-- and was truncated to "...or one on a task you c", which would have left this
-- repository and the database disagreeing about its name and any later
-- `drop policy` by the written name failing. The whole sentence is in the
-- comment above, where it cannot be cut.
create policy "Attachments: delete a file you attached, or one on your task"
  on storage.objects
  for delete
  to authenticated
  using (
    bucket_id = 'attachments'
    and (select public.is_active())
    and public.attachments_task_id(objects.name) is not null
    -- can you still see the task?
    and exists (
      select 1
      from public.tasks t
      where t.id = public.attachments_task_id(objects.name)
    )
    and (
      -- did you upload it?
      objects.owner_id::text = (select auth.uid())::text
      -- or did you create the task?
      or exists (
        select 1
        from public.tasks creator
        where creator.id = public.attachments_task_id(objects.name)
          and creator.owner_id = (select auth.uid())
      )
    )
  );

-- 6.4 NO UPDATE POLICY, and this is the justification rather than an omission.
--
-- "Replace or rename: nobody" (issue #237). Row-level security refuses what no
-- policy allows, so the absence IS the rule, and it closes two doors with one
-- silence:
--
--   * a file's bytes never change under a signed link somebody already holds.
--     Replacing them would mean a link issued for one photograph opening a
--     different one.
--   * and nothing can be renamed, which is what keeps section 2 meaningful: a
--     rename is a change of `name`, and `name` is where the task id lives, so a
--     permitted rename would be a permitted move of a file from one task to
--     another -- past every rule in this file, because the rules ask about the
--     path.
--
-- IT IS ALSO WHAT REFUSES UPSERT, which is worth saying because an upload is
-- otherwise an insert and this would look irrelevant to it. "To allow
-- overwriting files using the `upsert` functionality you will need to
-- additionally grant `SELECT` and `UPDATE` permissions"
-- (https://supabase.com/docs/guides/storage/security/access-control, read
-- 2026-10-08). SELECT is granted in 6.1 and UPDATE is not, so an upload asking
-- to overwrite is refused while an upload to a fresh path is not.

-- ---------------------------------------------------------------------------
-- 7. A task that still has files cannot be deleted
-- ---------------------------------------------------------------------------
--
-- "The owner decided on 2026-10-08 that leftover files are not acceptable."
-- docs/plan.md's two mechanisms, of which this file is the second and the one
-- that makes it a property of the database rather than of one code path: "the
-- database refuses to delete a task that still has files ... whatever asked it
-- to. A row deleted in the SQL editor, by a server function, or by a cascade
-- from somewhere else all meet this one."
--
-- WHY A TRIGGER AND NOT A FOREIGN KEY. There is no foreign key available:
-- nothing in Supabase connects storage.objects to this project's tasks table --
-- its columns are id, bucket_id, name, created_at, updated_at, metadata,
-- path_tokens, version and owner_id
-- (https://supabase.com/docs/guides/storage/schema/design, read 2026-10-08) --
-- and not one of them is a reference to a task. The link has to be made rather
-- than inherited, and it has to be made where every path goes through it.
--
-- WHY A TRIGGER AND NOT A POLICY, which is the sharper half. A policy is only
-- evaluated for roles it names, and it is not evaluated at all for the table's
-- owner or for a role with bypassrls -- which is to say not for service_role,
-- not for the owner in the dashboard, and not for whatever applies a migration.
-- A TRIGGER FIRES FOR ALL OF THEM. "By anyone, through any path" is a sentence
-- only a trigger can keep.
--
-- AND IT FIRES ON A CASCADE, which docs/plan.md and docs/architecture.md both
-- mark NOT CONFIRMED: "whether a refusal fires on a cascade the way it fires on
-- a direct delete is a question about Postgres that this plan has not answered
-- by reading or by trying." It is answered by trying, in
-- evidence/build-it-23-attachments-bucket.md, on a local sandbox: deleting the
-- auth.users row cascades to public.tasks and this trigger refuses it, so
-- deleting an account is refused while any of that person's tasks still has a
-- file. That is what makes the Build it 26 requirement ("deleting a person's
-- account removes that person's files", issue #235) something nobody can get
-- past rather than something somebody has to remember.
--
-- WHAT IT MEANS FOR DELETING A TEAM: nothing, and that is worth stating because
-- it looks as though it should mean something. public.tasks.team_id is
-- `references public.teams (id) on delete set null`
-- (20261002133637_tasks_join_teams.sql), so deleting a team UPDATES its tasks
-- rather than deleting them -- each returns to its creator as a personal task,
-- with its files still on it, now visible to that one person. This trigger
-- never fires. And a team cannot be deleted through the app at all today:
-- public.teams has no delete policy and no server function deletes one, so the
-- only paths are the owner's hand in the dashboard and an account deletion
-- cascading through teams.owner_id -- the second of which is refused by this
-- trigger first, through that person's own tasks, before it ever reaches their
-- teams.
--
-- THE MESSAGE NAMES NO FILE, and that is a rule rather than a style choice.
-- docs/plan.md: "a storage error is reported with its code and the operation,
-- never with the path or the name", because a file name is free text somebody's
-- phone chose or somebody typed. It does not say how many files either: the
-- count is a fact about the task that the person asking may not be able to see
-- every part of.
--
-- 23503 is foreign_key_violation, chosen because it is the code a reader takes
-- as "something still points at this row", which is exactly what is true. It is
-- deliberately not the 42501 the column guard on this table raises, which means
-- "you may not": this refusal is not about permission, and after the owner's
-- decision on who may delete a file it is not about permission in any case --
-- a task's creator may delete every file on their own task, so a refusal here
-- means the files are still there, which is a thing the person can act on.
--
-- security definer, because it reads storage.objects and the caller has no
-- business being able to. It is the one function here whose owner needs a
-- privilege on a Supabase-managed table: UNVERIFIED whether the role that
-- applies migrations holds SELECT on storage.objects. If it does not, this
-- trigger raises for every task deletion, which is loud rather than quiet.
create function public.tasks_refuse_delete_with_files()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if exists (
    select 1
    from storage.objects o
    where o.bucket_id = 'attachments'
      and public.attachments_task_id(o.name) = old.id
  ) then
    raise exception 'This task still has files. Remove its files first, then delete the task.'
      using errcode = '23503';
  end if;

  return old;
end;
$$;

comment on function public.tasks_refuse_delete_with_files() is
  'Trigger on public.tasks. Refuses to delete a task while any object remains under attachments/<task id>/, whatever asked -- a screen, a server function, the SQL editor, or a cascade from auth.users. It is a trigger rather than a policy because a policy is not evaluated for service_role, for the table''s owner, or for a cascade. The message names no file and no count: docs/plan.md forbids a file name in an error.';

-- EXECUTE on a trigger function is not checked when the trigger fires, and a
-- trigger function cannot be called directly -- PostgreSQL answers "trigger
-- functions can only be called as triggers" -- so none of these grants serves
-- anything and taking them away costs nothing.
--
-- 20261002133637's twin revoked from PUBLIC alone (#84), and the read-back in
-- evidence/build-it-23-attachments-bucket.md section 3 shows what that leaves:
-- anon and authenticated still holding EXECUTE, because Supabase grants it to
-- them BY NAME and a revoke from PUBLIC does not touch a grant made by name. It
-- is harmless, and a grant nobody can use is still a grant somebody has to work
-- out is harmless, so all four lines are written here.
revoke execute on function public.tasks_refuse_delete_with_files() from public;
revoke execute on function public.tasks_refuse_delete_with_files() from anon;
revoke execute on function public.tasks_refuse_delete_with_files() from authenticated;
revoke execute on function public.tasks_refuse_delete_with_files() from service_role;

-- BEFORE, not AFTER: a BEFORE row trigger can refuse the deletion before the row
-- goes, which is the point. FOR EACH ROW, because the question is about one task.
--
-- A SECOND TRIGGER ON THIS TABLE, and it does not disturb the first.
-- tasks_enforce_column_rules is `before insert or update`, so the two never fire
-- on the same statement and there is no order between them to get right.
create trigger tasks_refuse_delete_with_files
  before delete on public.tasks
  for each row
  execute function public.tasks_refuse_delete_with_files();

-- ---------------------------------------------------------------------------
-- 8. The one grant this file writes on an existing table, and why
-- ---------------------------------------------------------------------------
--
-- Every policy in section 6 reads public.tasks in a subquery, and a policy's
-- expression is evaluated with the privileges of the role making the request. So
-- all three rules rest on `authenticated` holding SELECT on public.tasks.
--
-- IT ALREADY DOES, and this line therefore grants nothing today. No migration in
-- this repository has ever granted a table privilege: the app reaches
-- public.tasks as `authenticated` on staging because Supabase grants select,
-- insert, update and delete on every table in the public schema to anon,
-- authenticated and service_role -- its changelog of 28 April 2026, "Breaking
-- Change: Tables not exposed to Data and GraphQL API automatically", quoted in
-- 20261004114313_suspend_accounts.sql and in evidence/build-it-15-part-1.md.
--
-- IT IS WRITTEN BECAUSE ISSUE #237 ASKS FOR EVERY GRANT EXPLICITLY, and because
-- a permission that exists only through a default nobody wrote is a permission
-- nobody can see. Supabase applies "new public tables are not exposed by
-- default" to existing projects on 30 October 2026 (changelog 45329, issue
-- #130); #130's own sandbox settled that the change alters DEFAULT privileges,
-- so "the old table keeps its grants, the new one has none" -- which means
-- public.tasks keeps what it has and this line is belt-and-braces rather than a
-- fix. An explicit grant is not a default and is not withdrawn by a change to
-- defaults.
--
-- IT IS THE NARROWEST THING THAT WORKS: select, on one table, for one role.
-- Nothing here grants insert, update or delete, and nothing here grants anon
-- anything.
grant select on table public.tasks to authenticated;

-- ---------------------------------------------------------------------------
-- 9. What this migration does NOT do
-- ---------------------------------------------------------------------------
--
-- Written here as well as in the pull request, because the gap between "the
-- rules exist" and "a person can attach a file" is the whole of Build it 23's
-- remaining work, and a reader of this file should not have to guess at it.
--
--   * NOTHING CAN UPLOAD. No screen, no Edge Function, no client code. The
--     bucket is created empty and nothing in this repository puts anything in
--     it.
--   * NOTHING COUNTS ON THE SERVER. docs/plan.md's "enforced on the server at
--     upload" is still owed, and section 5 says exactly why this file does not
--     discharge it: an upload made with the service-role key is not evaluated
--     against any policy here.
--   * NOTHING DELETES A TASK'S FILES. Section 7 refuses to delete a task that
--     still has files; the other half of docs/plan.md's decision -- "the app
--     deletes all the files, then the task" -- is code that does not exist yet.
--     Until it does, a task with a file on it cannot be deleted at all. Nothing
--     can put a file there, so nothing is stuck today.
--   * NOTHING REMOVES A PERSON'S FILES WHEN THEIR ACCOUNT GOES. That is a
--     requirement of Build it 26 (issue #235). Section 7 is what makes it
--     unavoidable rather than aspirational: until it is built, deleting an
--     account with files is refused.
--   * AND A SIGNED LINK IS STILL A CREDENTIAL FOR FIVE MINUTES. No rule in this
--     file can reach a link that has already been made. docs/plan.md, "Links,
--     and what an unexpired one allows".
--
-- AND ONE THING NOTHING IN THIS FILE MAY EVER BE USED FOR, which the issue asked
-- to be established and which decides how the deletion half must be written:
-- "Deleting objects via a SQL query will not remove the object from the bucket
-- and will result in the object being orphaned"
-- (https://supabase.com/docs/guides/storage/management/delete-objects, read
-- 2026-10-08), and the schema page says the same of every operation: "All
-- operations, including uploading, copying, moving, and deleting, should
-- exclusively go through the API"
-- (https://supabase.com/docs/guides/storage/schema/design, read 2026-10-08).
--
-- So the DELETE policy in 6.3 is what PERMITS a deletion; it is not a way to
-- perform one. `delete from storage.objects` removes the app's knowledge of a
-- file and leaves the bytes behind, paid for and unreachable -- which is the
-- exact outcome the owner's "leftover files are not acceptable" decision
-- forbids. Whatever Build it 23 writes to delete a task's files must call the
-- Storage API's remove, and the policy above is what lets the API through.
-- Section 7's trigger is unaffected: it only READS storage.objects, and a row
-- that is still there is the right answer to "does this task still have files?"
