-- Suspend accounts: account_status, is_active(), and one restrictive rule per table.
--
-- Build it 16, step 5, part A of two (issue #128). THE DATABASE ONLY. No screen
-- and no server function changes go with this migration, on purpose. Part B
-- changes create-team, invite-member and accept-invite, which this migration
-- cannot reach -- see "What part B must do" at the end of this file, and the
-- pull request, which lists it too.
--
-- docs/plan.md, "Suspending an account", added 2026-10-04 before this migration
-- was written (rule 9): "the owner can stop one account from reading or changing
-- anything -- their own tasks, their teams, everything -- without deleting the
-- account or its work ... Removing the row restores them exactly as they were."
--
-- THIS MIGRATION HAS NOT BEEN APPLIED ANYWHERE. Not local, not staging, not
-- production. Rule 19: the assistant does not run `db push` anywhere, and the
-- guard refuses every `db push` except `--local`.
--
-- Three pieces, and the order they are written in is forced:
--
--   1. public.account_status   a row means that person is suspended
--   2. public.is_active()      reads that table, which the app cannot
--   3. five restrictive rules  one per table, for every command
--
-- The table comes first because the function reads it, and the function comes
-- before the rules because a policy cannot name a function that does not exist
-- yet. 20261002122203_team_rules.sql had the same constraint for the same reason.
--
-- WHAT THIS CHANGES ABOUT WHO SEES WHAT. For anybody with no row in
-- account_status -- which is everybody, the moment this is applied -- nothing
-- changes at all. Every existing rule still decides, and the rule added here
-- is ANDed with it as `true`. For somebody with a row, every one of the five
-- tables refuses them, for every command. There is no middle state.
--
-- WHAT IT DELIBERATELY DOES NOT DO, because the plan says so: no screen, no
-- self-service, no notification, no history. The owner adds and removes the row
-- by hand in the dashboard. Nothing in this repository writes to this table.
--
-- DO NOT EDIT THIS FILE once it has been applied anywhere. A migration is
-- applied once; editing an applied one leaves the repository and every database
-- that has already run it silently disagreeing, and the edit reaches none of
-- them. To change any of this, add a new migration.
--
-- Where this migration has been applied is recorded in docs/environments.md and
-- evidence/, not here -- a status note kept in this file goes stale without
-- anyone noticing.

-- ---------------------------------------------------------------------------
-- 1. account_status -- one row per suspended person
-- ---------------------------------------------------------------------------
--
-- A ROW IS THE WHOLE OF THE STATE. There is no `suspended boolean` to get out of
-- step with itself: present means suspended, absent means not. A boolean column
-- would allow a row that says `false`, which is a third state meaning nothing,
-- and every query would have to remember to check it.

create table public.account_status (
  -- The primary key IS the auth user id, as profiles does. One row per person,
  -- no second id to keep in step, and no way to be suspended twice. Deleting
  -- the account takes the row with it: a suspension cannot outlive the person
  -- it names.
  user_id uuid primary key
    references auth.users (id) on delete cascade,

  -- When. Defaulted, so the owner suspending somebody by hand cannot forget to
  -- set it, and `not null` so there is no row that cannot say when it started.
  suspended_at timestamptz not null default now(),

  -- Why, optional. docs/plan.md's appendix marks this SENSITIVE: it is free
  -- text, and it is text ABOUT A PERSON, so it can name a third party who never
  -- agreed to anything. The plan asks for it to be "short and factual: it is a
  -- note to the owner, not a case file about a person."
  --
  -- NO LENGTH CONSTRAINT, and that is a decision rather than an omission. Every
  -- other free-text column here is capped -- tasks.title at 200,
  -- profiles.display_name at 40 -- because a USER types into it, and a cap is
  -- the only thing standing between a text column and a notes field. Nothing
  -- types into this one: no screen writes it, the app has no privilege to write
  -- it (see the revoke below), and the only author is the owner in the
  -- dashboard. A cap here would restrain nobody but the owner, and would do it
  -- by truncating the explanation of why somebody was cut off.
  --
  -- null means no reason was given. The app never reads this column, so nothing
  -- has to handle that.
  reason text
);

comment on table public.account_status is
  'One row per suspended person: a row means that person is refused by every rule on tasks, teams, team_members, invitations and profiles. Removing the row restores them. No policy and no privilege for anon or authenticated, so nothing in the app can read or write it; the owner adds and removes rows by hand. reason is free text about a person -- see docs/plan.md.';

-- No index beyond the primary key. The only question ever asked of this table
-- is "is there a row for this user_id?", which the primary key answers.

-- Without this line, the absence of policies below would mean nothing at all.
alter table public.account_status enable row level security;

-- AND NO POLICIES, on purpose. Row-level security refuses what no policy
-- allows, so this is the whole of the app's access to this table: none.
--
-- That is the second of two locks, and it is the weaker one. The first is the
-- revoke below. Privileges are checked BEFORE row-level security, so a caller
-- without the privilege never reaches the question of which rows it may see --
-- which is why the revoke, and not this line, is what makes the table
-- unreachable. This line is here so that a future `grant` by accident does not
-- immediately open the table as well.

-- WHO MAY REACH THIS TABLE AT ALL.
--
-- Supabase grants table privileges on a new table in the public schema to anon,
-- authenticated and service_role by itself. Its changelog of 28 April 2026,
-- "Breaking Change: Tables not exposed to Data and GraphQL API automatically",
-- says of an existing project: "select, insert, update, and delete are granted
-- to every table in the `public` schema to the `anon`, `authenticated` and
-- `service_role` roles." No migration in this repository grants a table
-- privilege, and the app reaches public.tasks as `authenticated` on staging
-- (evidence/build-it-15-part-1.md), which is that default at work.
--
-- So this table arrives readable and writable by the app, and the line below is
-- what closes it. Not a precaution against a hypothetical: without it, any
-- signed-in person could read who is suspended and why -- the free text about a
-- person that docs/plan.md marks sensitive -- and could delete their own row to
-- un-suspend themselves.
--
-- PUBLIC is not named, because a new table grants PUBLIC nothing, so there
-- would be nothing to revoke. anon and authenticated are the two roles the
-- Data API uses, and they are named explicitly rather than relying on the
-- project's default privileges staying as they are.
revoke all on table public.account_status from anon, authenticated, service_role;

-- service_role is revoked above with the others and then given SELECT back, so
-- that it has exactly one privilege here and no others. Two reasons, and the
-- first is the one that stops part B being broken on arrival:
--
--   1. PART B HAS TO READ THIS TABLE. The three server functions use the admin
--      client, which connects as service_role, and service_role bypasses
--      row-level security -- the Supabase roles page says of it, "This role is
--      used by the API (PostgREST) to bypass Row Level Security." So the five
--      rules below are never evaluated for those functions, and part B must ask
--      this question itself. It cannot do that without select.
--
--      Granting it HERE rather than leaning on the project default also makes
--      part B survive a date: on 30 October 2026 Supabase applies "tables in
--      public are not exposed by default" to all existing projects, and its own
--      fix revokes from service_role too. A table created after that date with
--      no explicit grant would be unreachable by the server functions, and the
--      only symptom would be a 42501 from part B. See issue #130.
--
--   2. NOTHING IN THE APP MAY WRITE IT. insert, update and delete are not
--      granted back, so no server function can suspend anybody, restore
--      anybody, or edit a reason, even by mistake. docs/plan.md: the owner adds
--      and removes the row by hand, and there is no admin page in this version.
--      If a "suspend from a screen" feature is ever agreed, it updates the plan
--      first and grants what it needs then, in its own migration, with a reason.
grant select on table public.account_status to service_role;

-- ---------------------------------------------------------------------------
-- 2. is_active() -- the one question every rule below asks
-- ---------------------------------------------------------------------------
--
-- "Is the person making this request allowed to do anything?" False when nobody
-- is signed in, false when the signed-in person has a row in account_status,
-- true otherwise.
--
-- WHO IS ASKING IS NEVER AN ARGUMENT, exactly as with public.is_team_member:
-- the function reads auth.uid() inside its own body. There is deliberately no
-- user_id parameter. One that took one would answer questions about other
-- people -- "is Carol suspended?" -- which is a different question, and one no
-- signed-in person should be able to ask about anybody else. This function has
-- no parameters at all, so there is nothing to pass.
--
-- IT NEVER RETURNS NULL, which matters more here than it looks. A policy treats
-- null as "no", so a null would refuse rather than admit, but it would refuse
-- for a reason nobody could read off the expression. Both halves below are
-- total: `auth.uid() is not null` is true or false, never null, and `not exists`
-- is true or false, never null. So the answer is always one of two things.
--
-- THE SIGNED-OUT CASE IS false, not true, and that is the fail-closed
-- direction. It makes no practical difference to the five rules below -- each is
-- limited to the authenticated role, and a signed-out caller matches no
-- permissive policy on any of those tables anyway -- but this function will be
-- read by whoever writes part B, and "no session means not active" is the answer
-- that cannot be misused.
--
-- security definer, so it runs as the role that owns it (postgres, which
-- applied this migration) rather than as the caller. That is the whole point:
-- it has to read a table the caller has no privilege on at all. Reading
-- account_status as the caller would fail with 42501 for every single query
-- against all five tables, because a policy's expression is evaluated with the
-- caller's privileges.
--
-- Running as postgres is why the two guards below matter, and the reasoning is
-- 20261002122203_team_rules.sql's, unchanged:
--
--   set search_path = ''  so no schema is searched implicitly. A function
--                         running with more rights than its caller must not
--                         resolve a name through a path somebody else can
--                         change, or it can be made to call their function
--                         instead of the one written here.
--   schema-qualified      the consequence of the line above: with an empty
--                         search path, public.account_status and auth.uid() must
--                         each be written in full or they do not resolve at all.
--   stable                it reads a table and changes nothing, so Postgres may
--                         work it out once per query rather than once per row.
create function public.is_active()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select auth.uid() is not null
    and not exists (
      select 1
      from public.account_status s
      where s.user_id = auth.uid()
    );
$$;

comment on function public.is_active() is
  'False when nobody is signed in, or when the signed-in person has a row in public.account_status; true otherwise. Takes no arguments: who is asking comes from auth.uid() inside the body, so it can never be asked about somebody else. security definer because it reads a table the app has no privilege on.';

-- WHO MAY CALL IT: authenticated, and nobody else. The same three lines
-- 20261002122203_team_rules.sql uses for is_team_member, for the same reasons,
-- and issue #128 asks for them by name.
--
-- Postgres grants execute on a new function to PUBLIC automatically, and a
-- function in the public schema is published by PostgREST as an RPC endpoint --
-- so "PUBLIC" here means anybody who can reach the API with the publishable
-- key. Revoking from PUBLIC closes that door before it is ever open.
--
-- anon is named SEPARATELY, and here that is not belt-and-braces: Supabase
-- grants execute on new functions to anon BY NAME as well, which is a different
-- grant from the one PUBLIC holds. Revoking from PUBLIC does not remove it. The
-- line below is what actually stops a signed-out caller invoking this.
--
-- What a signed-out caller would learn is admittedly little -- auth.uid() is
-- null for anon, so it answers false for everybody. The reason to bother is
-- that this is a security definer function reading a table nothing else may
-- read, and the rule for that kind of function is to grant the narrowest thing
-- that works and nothing wider.
--
-- authenticated is what the five rules below need. A policy's expression is
-- evaluated with the privileges of the role making the request, so without this
-- grant every rule below would fail with 42501 for the app's own users -- which
-- is to say the app would stop working entirely, for everybody, suspended or
-- not.
--
-- SERVICE_ROLE IS NOT GRANTED BY THESE THREE LINES, AND CAN EXECUTE THIS
-- FUNCTION ANYWAY. That is stated plainly because the obvious reading of the
-- three lines below is that `authenticated` ends up with EXECUTE and nobody
-- else, and that is not what happens.
--
-- Supabase grants EXECUTE on a new function in the public schema to anon,
-- authenticated AND service_role, each by name. The revokes below name public
-- and anon, so the service_role grant is never touched and survives. Read back
-- from the sandbox after applying this file:
--
--   is_active       {postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}
--   is_team_member  {postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}
--
-- Identical, which is the point: this file does exactly what
-- 20261002122203_team_rules.sql does, as issue #128 asked. That file's comment
-- claims "service_role is deliberately NOT granted", which is not true of
-- either function. Filed as issue #131 -- a wrong comment rather than a hole,
-- and not fixed here, because fixing it would mean editing an applied migration.
--
-- It is harmless. service_role has select on account_status (granted above) and
-- bypasses row-level security, so being able to ask this question tells it
-- nothing it could not already find out.
--
-- PART B MUST NOT CALL THIS FUNCTION, and that is the real reason the paragraph
-- above is here rather than in the pull request. is_active() answers about
-- auth.uid(), and an admin-client connection has no signed-in user -- so
-- auth.uid() is null and the answer is FALSE FOR EVERY CALLER. A server function
-- that asked this would refuse everybody, and would do it without an error,
-- which is the quiet kind of wrong. Proved in the sandbox: as service_role with
-- no session, is_active() returns f. Part B reads public.account_status for the
-- specific user id instead, which is what the select granted above is for.
revoke execute on function public.is_active() from public;
revoke execute on function public.is_active() from anon;
grant execute on function public.is_active() to authenticated;

-- ---------------------------------------------------------------------------
-- 3. The five rules
-- ---------------------------------------------------------------------------
--
-- One RESTRICTIVE policy per table, for ALL commands, to authenticated, with
-- `using` and `with check` both calling is_active(). Five policies, all
-- identical but for the table name.
--
-- WHY RESTRICTIVE AND NOT AN EDIT TO EACH EXISTING RULE. Issue #128 asks for the
-- reasoning if the other way is chosen; this is the reasoning for choosing this
-- way.
--
-- Policies of the same kind are combined, and the two kinds combine differently:
-- PERMISSIVE policies are OR-ed together, RESTRICTIVE policies are AND-ed on
-- top. So one restrictive rule is a single gate in front of everything, and
-- `is_active() and (whatever the existing rules decide)` is exactly the sentence
-- this feature wants.
--
-- Editing the existing rules instead would mean adding `and (select
-- public.is_active())` to 11 expressions across 5 tables -- invitations 1,
-- profiles 3, tasks 4, team_members 2, teams 1, counted on a local sandbox built
-- from these migrations. That is worse in three ways that matter:
--
--   * 11 chances to miss one, and a missed one is a hole that looks like
--     nothing. Here there are 5 rules and each covers its whole table.
--   * every future policy would have to remember the extra clause. A restrictive
--     rule applies to commands, not to policies, so a policy added next year is
--     covered without anybody remembering anything.
--   * it would mean editing applied migrations, which this repository forbids
--     at the top of every one of them, or re-creating 11 policies in this file
--     to add one condition to each.
--
-- A RESTRICTIVE POLICY GRANTS NOTHING, which is the thing most likely to be
-- misread about what follows. It can only take access away. So teams still has
-- no insert, update or delete policy and still refuses all three; profiles still
-- has no delete policy; team_members still has no insert or update policy.
-- Adding a rule "for all commands" does not give anybody a command they did not
-- have.
--
-- `to authenticated`, matching every existing rule on these tables. anon is left
-- alone deliberately: it matches no permissive policy on any of the five, so it
-- already sees nothing and can write nothing, and naming it here would add a
-- condition to a path that is already closed.
--
-- `(select public.is_active())` is wrapped in a select on purpose, as every rule
-- in this schema wraps `(select auth.uid())`: Postgres then works it out once per
-- query instead of once per row.
--
-- WHAT `for all` MEANS FOR EACH COMMAND, because it is not "using applies to
-- everything". With both halves written, as here, `using` is the read side and
-- `with check` is the new-row side:
--
--   select  using only            -> a suspended person matches no rows
--   delete  using only            -> matches no rows, so DELETE 0, no error
--   update  using AND with check  -> matches no rows, so UPDATE 0, no error
--   insert  with check only       -> the new row is refused, WITH an error:
--                                    "new row violates row-level security
--                                    policy for table ..."
--
-- So three of the four are silent and one raises. That is the same shape every
-- other rule in this schema has, and it is why issue #128 asks for "return
-- nothing or are refused" rather than for an error every time.
--
-- ONE CONSEQUENCE WORTH KNOWING BEFORE THIS IS APPLIED, and it is not a hole.
-- public.team_roster is a view, and a view cannot have a policy. It does not
-- need one: 20261002122203_team_rules.sql created it `with (security_invoker =
-- true)`, so it reads teams, team_members and profiles as the person asking, and
-- all three of those are covered below. A suspended person selecting from
-- team_roster gets nothing.

-- tasks. Four permissive policies today, one per command.
create policy "Suspended accounts are refused everything"
  on public.tasks
  as restrictive
  for all
  to authenticated
  using ((select public.is_active()))
  with check ((select public.is_active()));

-- teams. One permissive policy today, for select only. The other three commands
-- were already refused and stay refused.
create policy "Suspended accounts are refused everything"
  on public.teams
  as restrictive
  for all
  to authenticated
  using ((select public.is_active()))
  with check ((select public.is_active()));

-- team_members. Two permissive policies today: select, and the team owner's
-- delete.
create policy "Suspended accounts are refused everything"
  on public.team_members
  as restrictive
  for all
  to authenticated
  using ((select public.is_active()))
  with check ((select public.is_active()));

-- invitations. One permissive policy today, the team owner's select. A suspended
-- owner stops seeing their own team's pending invitations, which is the intent:
-- "stop one account from reading or changing anything".
create policy "Suspended accounts are refused everything"
  on public.invitations
  as restrictive
  for all
  to authenticated
  using ((select public.is_active()))
  with check ((select public.is_active()));

-- profiles. Three permissive policies today: insert, select, update. Note what
-- this means for a suspended person's team mates: THEY are unaffected, and can
-- still read the suspended person's nickname. This rule is about what the
-- suspended person may do, not about hiding them from everybody else. Hiding a
-- suspended person from their team would be a different feature, and docs/plan.md
-- does not ask for it.
create policy "Suspended accounts are refused everything"
  on public.profiles
  as restrictive
  for all
  to authenticated
  using ((select public.is_active()))
  with check ((select public.is_active()));

-- ---------------------------------------------------------------------------
-- The trigger on tasks is untouched, on purpose
-- ---------------------------------------------------------------------------
--
-- tasks_enforce_column_rules stays exactly as 20261002133637_tasks_join_teams.sql
-- created it. It is about which COLUMNS may differ after a change, which is a
-- different question from whether the person may act at all.
--
-- It does change which MESSAGE a suspended person sees in one case, and that is
-- worth writing down rather than discovering. A BEFORE ROW trigger runs before a
-- policy's `with check` is evaluated, so for an INSERT the trigger speaks first:
--
--   a suspended person adding a PERSONAL task          -> the trigger passes it,
--                                                         then with check
--                                                         refuses: "new row
--                                                         violates row-level
--                                                         security policy"
--   a suspended person adding a task to a team they
--   are NOT in                                         -> the trigger refuses
--                                                         first: "A task can
--                                                         only be added to a
--                                                         team its creator
--                                                         belongs to."
--
-- Both are refusals and nothing is written either way. For update, delete and
-- select the trigger never gets a say, because `using` matches no rows and so
-- there is no row for a BEFORE UPDATE trigger to fire on.

-- ---------------------------------------------------------------------------
-- What part B must do, and why this migration cannot
-- ---------------------------------------------------------------------------
--
-- THE FIVE RULES ABOVE DO NOT APPLY TO create-team, invite-member OR
-- accept-invite. All three use ctx.supabaseAdmin, which connects as
-- service_role, and service_role bypasses row-level security -- so a suspended
-- person can still create a team, still invite people to it, and still accept an
-- invitation, because the only checks on those paths are the ones written in
-- TypeScript, and none of them has heard of account_status.
--
-- That is not an oversight in this migration; it is the limit of what a database
-- rule can reach. Issue #128 says to list it and change nothing, so the full
-- list is in the pull request and summarised here:
--
--   create-team    after `const ownerId = ctx.userClaims?.id`, before the
--                  "at most 3 teams" count: refuse a caller with an
--                  account_status row.
--   invite-member  after `const callerId = ctx.userClaims?.id`, before the team
--                  lookup, and so before any email is decided or sent.
--   accept-invite  after the userId/userEmail checks and BEFORE the atomic claim
--                  -- the claim is one-shot, and claiming an invitation for
--                  somebody who is then refused burns it for good.
--
-- Each reads public.account_status with the admin client, which is what the
-- `grant select ... to service_role` above exists for, and each must fail CLOSED
-- on a read error: an unknown is not "not suspended". This project has made that
-- mistake's shape explicit before -- invite-member's own comments say "an unknown
-- is not a zero" about its two counts.
--
-- AND NONE OF THEM CALLS is_active(). It would not error, which is what makes it
-- dangerous: on an admin connection auth.uid() is null, so the answer is false
-- for everybody and all three functions would refuse every caller. See the
-- paragraph above the revokes in part 2.
