-- Tasks join teams: tasks.team_id, member-level rules, and the column guard.
--
-- Build it 15, part 1 of 4 (issue #82). THE EXPAND STEP, AND THE DATABASE ONLY.
-- No app or UI code goes with this migration, on purpose: the schema is proved on
-- staging and then in production before any screen depends on it. Part 2 builds
-- the screens. A later CONTRACT migration removes the three owner-only rules this
-- one leaves standing -- see "What the contract step does" at the end, which
-- names exactly which ones go and which one stays.
--
-- docs/plan.md, features 4 and 5, as updated by this pull request: a task is
-- either PERSONAL or belongs to ONE OF YOUR TEAMS. Every member of that team can
-- see it, tick it and rename it. Only the person who created it can delete it.
--
-- Before this migration a task belonged to one person and nobody else could see
-- it. That is the whole of what changes here, and it changes in five pieces:
--
--   1. tasks.team_id          optional, references teams, on delete set null
--   2. three new policies     read, change and add -- added ALONGSIDE the
--                             existing owner-only ones, which are NOT touched
--   3. a column guard         a trigger: owner_id can never change, and only the
--                             creator may move a task between teams
--   4. an index on team_id
--   5. no delete policy       the existing owner-only one is already the rule
--                             this feature wants, so there is nothing to add
--
-- WHAT THIS CHANGES ABOUT WHO SEES WHAT. A team task becomes readable and
-- changeable by every member of its team. Nothing that was visible stops being
-- visible: every new rule below returns every row the matching owner-only rule
-- returned, and some more. A PERSONAL task -- team_id null, which is every task
-- that exists today -- stays exactly as private as it was.
--
-- ONE CONSEQUENCE WORTH KNOWING BEFORE THIS IS APPLIED. web/src/app/tasks/page.tsx
-- lists tasks with no owner filter and lets the select rule decide. After this
-- migration that page shows a team mate's team tasks mixed in with the person's
-- own, with no team label, and its "done" count counts them too. Delete still
-- refuses somebody else's task, so this is a wrong-looking screen and not a hole
-- -- and in practice nothing can create a team task until part 2, because no
-- screen sends a team_id. The screens are part 2's job, and there is an issue
-- filed alongside this migration that says so.
--
-- DO NOT EDIT THIS FILE once it has been applied anywhere. A migration is
-- applied once; editing an applied one leaves the repository and every database
-- that has already run it silently disagreeing, and the edit reaches none of
-- them. To change any of this, add a new migration.
--
-- Where this migration has been applied is recorded in docs/environments.md and
-- evidence/, not here -- a status note kept in this file goes stale without
-- anyone noticing.

-- ---------------------------------------------------------------------------
-- 1. tasks.team_id
-- ---------------------------------------------------------------------------
--
-- Optional, so "personal" is a real state and not a special team: a task with
-- team_id null belongs to its creator alone. Every task that exists today gets
-- null, which is why this column can be added without a backfill and without a
-- default.
--
-- ON DELETE SET NULL, AND WHY -- the issue asks for the decision and its cost.
--
-- When a team is deleted, each of its tasks loses its team_id and becomes a
-- personal task of the person who created it. The alternative, on delete cascade,
-- would delete the tasks with the team.
--
-- The deciding case is whose rows get destroyed. A team task may have been
-- written by any member, but a team is deleted by somebody else -- its owner, or
-- the removal of its owner's account, which cascades to teams through
-- teams.owner_id. Under cascade, Carol losing her own task because Alice closed
-- her account is a stranger deleting Carol's work, and this database has no
-- point-in-time restore on the free plan to undo it with (AGENTS.md rule 19).
-- Under set null, the row returns to the person who wrote it.
--
-- There is no orphan state to worry about, which is the usual argument for
-- cascade: "personal" is a state this table already has and the app already
-- draws. A task with no team is not a task in a broken state.
--
-- WHAT EACH MEMBER LOSES when a team is deleted, stated plainly:
--   * the team's tasks stop being shared -- each one returns to its creator, who
--     keeps it on their own list, with its title and its done tick intact;
--   * every other member stops seeing those tasks, because the only thing that
--     made them visible was the team;
--   * nobody loses a task they wrote themselves;
--   * which team a task used to be in is gone. team_id is overwritten with null,
--     not archived, and the teams row is gone too, so "it was in the Tuesday
--     crew's list" is not recoverable afterwards.
--
-- Nothing in the app can delete a team today: teams has no delete policy
-- (20260930101343_create_teams.sql) and no server function deletes one. So this
-- decision is about two paths -- the owner deleting a team by hand, and an
-- account deletion cascading into teams -- and about whatever "delete a team"
-- feature arrives later. It is settled now, in the migration that creates the
-- reference, rather than left to be settled in a hurry by whoever builds that.
alter table public.tasks
  add column team_id uuid references public.teams (id) on delete set null;

comment on column public.tasks.team_id is
  'The team this task belongs to, or null for a personal task. Every member of the team can read, tick and rename it; only its creator can delete it. On delete set null: deleting a team returns its tasks to their creators as personal tasks rather than destroying work written by other members.';

-- Every new rule below reads team_id, and the on delete set null action above
-- has to find a team's tasks by it. Worth an index.
--
-- NOT a partial index (where team_id is not null), though personal tasks will be
-- the majority and a partial index would be smaller: part 2's personal list asks
-- "team_id is null", and a partial index that excludes those rows cannot answer
-- it. A plain b-tree indexes nulls and can.
create index tasks_team_id_idx on public.tasks (team_id);

-- ---------------------------------------------------------------------------
-- 2. The new rules
-- ---------------------------------------------------------------------------
--
-- ADDED ALONGSIDE THE EXISTING OWNER-ONLY RULES, which 20260927182443_create_tasks.sql
-- created and this migration deliberately does not drop or alter. That is what
-- makes this an expand step: both sets of rules stand at once, so the database is
-- correct for the code before this change and for the code after it. Policies for
-- the same command are OR-ed, so while both stand, access is the WIDER of the two
-- -- and each new rule below is written to be a strict superset of its
-- owner-only twin, so "the wider of the two" is simply the new rule.
--
-- (select auth.uid()) is wrapped in a select on purpose: Postgres then works it
-- out once per query instead of once per row.
--
-- "team_id is not null and ..." is a short cut, not a correctness requirement.
-- public.is_team_member(null) is already false -- it asks whether a team with
-- that id is yours, and no team has a null id -- but spelling out the null case
-- saves a function call for every personal task and says out loud that a
-- personal task is never reachable through the team branch.

-- Who this lets in: the person who created the task, and -- if the task is in a
-- team -- every member of that team, the team's owner included. Who it keeps out:
-- a signed-in person who neither created it nor belongs to its team (Bob sees
-- nothing of Alice's team's tasks), and anybody signed out, because the rule is
-- limited to the authenticated role.
--
-- SUPERSET OF: "Owners can read their own tasks", whose whole condition is the
-- first line here.
create policy "Creators and team members can read a task"
  on public.tasks
  for select
  to authenticated
  using (
    (select auth.uid()) = owner_id
    or (team_id is not null and public.is_team_member(team_id))
  );

-- Who this lets in: the creator, and every member of the task's team -- to tick
-- it and to rename it. Who it keeps out: everybody else, and anybody signed out.
--
-- using says which rows may be changed. with check says what they may be changed
-- INTO, and it is deliberately NOT a copy of using: after the change the row must
-- be either a personal task of your own, or a task in a team you belong to. So a
-- member cannot quietly make a shared task personal, and nobody can push a task
-- into a team they are not in.
--
-- WHAT with check STILL CANNOT SAY is why the trigger in part 3 exists: this rule
-- sees only the finished row, so it cannot tell a tick from a change of owner,
-- and it cannot tell the creator moving their own task from a member moving
-- somebody else's. Read the two together -- the policy decides who may touch the
-- row, the trigger decides which columns may differ afterwards.
--
-- SUPERSET OF: "Owners can change their own tasks", which is the first line of
-- using. (Its with check is auth.uid() = owner_id, which is WIDER than the one
-- here for the creator of a task -- it would let Alice file her task into a team
-- she does not belong to. While both policies stand, that is exactly what the
-- trigger refuses, which is why the trigger is not optional in the expand step.)
create policy "Creators and team members can change a task"
  on public.tasks
  for update
  to authenticated
  using (
    (select auth.uid()) = owner_id
    or (team_id is not null and public.is_team_member(team_id))
  )
  with check (
    (team_id is null and (select auth.uid()) = owner_id)
    or (team_id is not null and public.is_team_member(team_id))
  );

-- Who this lets in: the signed-in person, adding a task as themselves -- either
-- personal, or into a team they belong to. Who it keeps out: anybody adding a
-- task in somebody else's name, anybody filing a task into a team they are not in
-- (Bob cannot add a task to Alice's team), and anybody signed out. with check is
-- the only half an insert has, and its first line pins owner_id to the caller, so
-- a request cannot create a task for somebody else.
--
-- NOT A SUPERSET, and this is the one place where "added alongside" is not
-- enough. "Owners can add tasks for themselves" checks only auth.uid() =
-- owner_id, which says nothing about team_id -- so while that rule stands,
-- insert policies being OR-ed means Bob could file a task into Alice's team by
-- sending her team's id with his own name on the row. The team half of this rule
-- is therefore enforced by the trigger below as well as here, and it is the
-- trigger that actually refuses Bob until the contract step removes the old rule.
create policy "You can add a task for yourself, or for a team you belong to"
  on public.tasks
  for insert
  to authenticated
  with check (
    (select auth.uid()) = owner_id
    and (team_id is null or public.is_team_member(team_id))
  );

-- NO NEW DELETE POLICY, on purpose. "Owners can remove their own tasks" from
-- 20260927182443_create_tasks.sql already says exactly what this feature wants --
-- only the creator can delete a task -- so there is nothing to add, and a second
-- delete policy would only be another rule to read. A member ticking and
-- renaming but not deleting is the point: the organiser's list does not lose
-- entries because somebody tidied up.
--
-- That policy is therefore NOT part of what the contract step removes. See the
-- end of this file.

-- ---------------------------------------------------------------------------
-- 3. The column guard
-- ---------------------------------------------------------------------------
--
-- "Members may tick and rename a team task, nothing more." A policy cannot say
-- that. It sees a whole row, before and after, and can only answer yes or no to
-- the change as a whole -- it cannot say "these two columns may differ and the
-- others may not", and it cannot compare the new row with the old one at all on
-- an insert. So the column limits are enforced here.
--
-- WHY A TRIGGER AND NOT COLUMN PRIVILEGES -- the issue asks for the choice to be
-- justified. Column privileges (revoke update (owner_id, team_id) on public.tasks
-- from authenticated) are per-ROLE, and every person using this app is the same
-- role: authenticated. So they cannot express either of the two rules that
-- matter. "owner_id can never change" they would get right by accident. "team_id
-- can change only by the creator, and only to a team they belong to" they cannot
-- express at all -- they would refuse the creator too, which is the one person
-- who is allowed to do it, and they would have nothing to say about WHICH team.
-- They also say nothing about an insert's team_id, which is the hole the old
-- insert policy leaves open. A trigger can see who is asking, the old row and
-- the new row at once, which is exactly what these rules are about.
--
-- WHAT IT ENFORCES, for every caller:
--
--   on insert   a team_id must name a team the row's OWNER belongs to.
--   on update   owner_id, id and created_at must not change, by anybody;
--               team_id may change only if the person asking is the creator,
--               and only to null or to a team the creator belongs to.
--
-- id and created_at are not in the issue's list. They are here because "nothing
-- more" is otherwise not true: both are writable through the API, and a member
-- who can rewrite created_at can reorder somebody else's list, while one who can
-- rewrite id can collide with another row. Four lines to make the sentence
-- literally true seemed better than a footnote saying it nearly is.
--
-- ON INSERT IT ASKS ABOUT THE ROW'S OWNER, NOT THE CALLER, and for app callers
-- those are the same question: both insert policies pin owner_id to
-- auth.uid(), so the row's owner IS the caller. Asking about the row keeps the
-- rule meaningful for a statement written by hand in the SQL editor, where
-- auth.uid() is null and there is no caller to ask about -- a hand-written row
-- still has to be coherent, rather than being waved through or refused outright.
--
-- security definer, so the two membership lookups run as the role that owns this
-- function (postgres, which applied this migration) rather than as the caller.
-- Without it the lookups would read public.teams and public.team_members through
-- their own row-level rules, and the answer to "does the row's owner belong to
-- this team?" would depend on what the CALLER is allowed to see -- which is a
-- different question, and one that would silently change if those read rules ever
-- changed. Running as the table's owner makes the check mean what it says.
--
-- Running with more rights than the caller is also why the two guards below
-- matter:
--   set search_path = ''  so no schema is searched implicitly. A function
--                         running with more rights must not resolve a name
--                         through a path somebody else can change.
--   schema-qualified      the consequence: public.teams, public.team_members and
--                         auth.uid() must each be written in full, or they do not
--                         resolve at all.
--
-- It does NOT call public.is_team_member(), though the policies above do. That
-- function answers only about the CALLER -- "who is asking is never an argument"
-- is the whole point of its design -- and two of the three checks here are about
-- the row's owner, who may be somebody else. So the membership test is written
-- out. It is the same test: owning the team, or having a team_members row for it.
--
-- EXECUTE IS LEFT AT THE POSTGRES DEFAULT, which is a grant to PUBLIC -- unlike
-- public.is_team_member, where 20261002122203_team_rules.sql revokes it. The
-- reason is a thing I could not verify rather than a difference of opinion:
-- PostgreSQL's CREATE TRIGGER page says the user CREATING a trigger needs execute
-- on its function, and says nothing about the user whose statement fires it. If
-- the check also happens at fire time, revoking execute from authenticated's
-- roles would refuse every insert and update of a task -- the whole feature, for
-- everybody -- and there is no database here to try it on (see the pull request).
-- Breaking writes to prove a point about a function nobody can usefully call is
-- the wrong trade. What is left exposed is small and worth naming: this function
-- takes no arguments and returns trigger, and the records it reads -- new and old
-- -- exist only when a trigger fires (PostgreSQL's PL/pgSQL trigger page: those
-- variables are created "when a PL/pgSQL function is called as a trigger"). So
-- there is nothing for a direct caller to make it do. Unverified: whether
-- PostgREST publishes a trigger-returning function as an endpoint at all.
create function public.tasks_enforce_column_rules()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    if new.team_id is not null
       and not exists (
         select 1
         from public.teams t
         where t.id = new.team_id
           and t.owner_id = new.owner_id
       )
       and not exists (
         select 1
         from public.team_members m
         where m.team_id = new.team_id
           and m.user_id = new.owner_id
       )
    then
      -- 42501 is insufficient_privilege, chosen so that a refusal reads as "you
      -- may not", which is what it is, rather than as a malformed request. The
      -- message names the rule rather than the row: it says nothing about the
      -- team, who is in it, or what the task says.
      raise exception 'A task can only be added to a team its creator belongs to.'
        using errcode = '42501';
    end if;

    return new;
  end if;

  -- From here on this is an update, so old is populated.

  if new.owner_id is distinct from old.owner_id then
    raise exception 'owner_id cannot change: a task stays with the person who created it.'
      using errcode = '42501';
  end if;

  if new.id is distinct from old.id then
    raise exception 'id cannot change.'
      using errcode = '42501';
  end if;

  if new.created_at is distinct from old.created_at then
    raise exception 'created_at cannot change.'
      using errcode = '42501';
  end if;

  if new.team_id is distinct from old.team_id then
    -- THE DELETED-TEAM CASE COMES THROUGH HERE TOO, and it is not somebody
    -- moving a task. team_id on this table is "on delete set null", and that
    -- action is performed as an ordinary update to this row, which fires this
    -- trigger: new.team_id null, old.team_id the team that has just gone. The
    -- person deleting the team is not the creator of every task in it, so
    -- without this branch deleting a team would be refused by this trigger --
    -- a guard about who may move a task quietly becoming a rule that teams can
    -- never be deleted.
    --
    -- Telling the two apart needs no flag: the foreign key's action runs after
    -- the teams row is gone, so inside this statement the old team no longer
    -- exists. Nobody can use this branch to make a shared task personal,
    -- because while the team exists the exists() below is true.
    if new.team_id is null
       and old.team_id is not null
       and not exists (
         select 1 from public.teams t where t.id = old.team_id
       )
    then
      return new;
    end if;

    if auth.uid() is distinct from old.owner_id then
      raise exception 'Only the person who created a task can move it between teams.'
        using errcode = '42501';
    end if;

    if new.team_id is not null
       and not exists (
         select 1
         from public.teams t
         where t.id = new.team_id
           and t.owner_id = old.owner_id
       )
       and not exists (
         select 1
         from public.team_members m
         where m.team_id = new.team_id
           and m.user_id = old.owner_id
       )
    then
      raise exception 'A task can only be moved into a team its creator belongs to.'
        using errcode = '42501';
    end if;
  end if;

  return new;
end;
$$;

comment on function public.tasks_enforce_column_rules() is
  'Trigger on public.tasks. Enforces what no policy can: owner_id, id and created_at never change; team_id changes only by the task''s creator and only to null or a team they belong to; and a new task''s team_id must name a team its creator belongs to. The last of those is also what refuses an outsider while the old owner-only insert policy still stands.';

-- BEFORE, not AFTER: a BEFORE row trigger can refuse the change before the row
-- is written, which is the point. FOR EACH ROW, because every rule above is about
-- one row's columns.
--
-- Not fired on delete, on purpose: who may delete a task is a whole-row question,
-- and the existing owner-only delete policy already answers it.
create trigger tasks_enforce_column_rules
  before insert or update on public.tasks
  for each row
  execute function public.tasks_enforce_column_rules();

-- ---------------------------------------------------------------------------
-- What the contract step does, when it comes
-- ---------------------------------------------------------------------------
--
-- Written down here because the thing most likely to go wrong in a contract step
-- is dropping one rule too many. Three policies from 20260927182443_create_tasks.sql
-- become redundant once part 2's screens are live, and ONE MUST STAY:
--
--   drop  "Owners can read their own tasks"        -- superset above
--   drop  "Owners can add tasks for themselves"    -- superset above, and the
--                                                     reason the trigger has to
--                                                     police insert today
--   drop  "Owners can change their own tasks"      -- superset above, and WIDER
--                                                     than it looks: its with
--                                                     check lets the creator
--                                                     file a task into a team
--                                                     they do not belong to
--   KEEP  "Owners can remove their own tasks"      -- this IS the delete rule for
--                                                     team tasks. Dropping it
--                                                     would leave tasks with no
--                                                     delete policy at all, and
--                                                     nobody could delete
--                                                     anything.
--
-- Nothing about the trigger changes in the contract step. It is not scaffolding
-- for the expand phase: it is the only thing that enforces the column limits in
-- either phase.
