-- Invitations and team membership: feature 3, "invite people to a team by email".
--
-- docs/plan.md, feature 3: "an invitation expires after 7 days, and a team may
-- have at most 20 pending."
--
-- Two tables, and the same shape as teams: a select rule and nothing else. No
-- insert, update or delete policy on either. With row-level security on, an
-- access that matches no policy is refused -- so the app, holding only the
-- publishable key, cannot create, change or delete an invitation or a membership
-- row at all. Both server functions hold the secret key instead:
--
--   invite-member  creates an invitation after checking the caller owns the team
--                  and that the team is under the 20-pending limit;
--   accept-invite  adds the team_members row and marks the invitation accepted.
--
-- The 20-pending limit is the reason there is no insert policy: a row-level rule
-- would have to count the team's other invitations, which is what a function is
-- for. See docs/architecture.md, "The arrows that carry a secret key".
--
-- DO NOT EDIT THIS FILE to change either table. A migration is applied once;
-- editing an applied one leaves the repository and every database that has
-- already run it silently disagreeing, and the edit reaches none of them. To
-- change a table, add a new migration.
--
-- Where this migration has been applied is recorded in docs/environments.md and
-- evidence/, not here -- a status note kept in this file goes stale without
-- anyone noticing.

-- ---------------------------------------------------------------------------
-- invitations
-- ---------------------------------------------------------------------------

create table public.invitations (
  id uuid primary key default gen_random_uuid(),

  -- Deleting a team takes its invitations with it. Nothing is left pointing at
  -- a team that no longer exists.
  team_id uuid not null
    references public.teams (id) on delete cascade,

  -- Stored lowercase, so the same address cannot be invited twice under
  -- different capitalisation, and so accept-invite can compare without
  -- worrying about case. The constraint below is what makes that true of every
  -- row rather than only the ones the function wrote.
  email text not null,

  -- A SHA-256 hash of the invitation token, hex-encoded: 64 characters.
  --
  -- THE TOKEN ITSELF IS NEVER STORED. It goes in one email and is never written
  -- down here. Until it expires or is used, that token is a credential -- anyone
  -- holding it can join the team -- so the database keeps only what is needed to
  -- recognise it, exactly as a password is kept as a hash. A leaked copy of this
  -- table therefore lets nobody join anything.
  token_hash text not null,

  -- Who sent it. Set by invite-member from the caller's verified token, never
  -- from the request body. If that account is deleted the invitation goes too.
  invited_by uuid not null
    references auth.users (id) on delete cascade,

  created_at timestamptz not null default now(),

  -- docs/plan.md: 7 days. Stored as an absolute moment rather than computed on
  -- read, so an invitation's life cannot be extended by a later code change,
  -- and so "expired" means the same thing to every query.
  expires_at timestamptz not null default (now() + interval '7 days'),

  -- Null until accepted. accept-invite sets it, and only where it is still
  -- null, which is what stops two clicks both succeeding.
  accepted_at timestamptz,

  constraint invitations_email_lowercase check (email = lower(email)),
  constraint invitations_email_not_blank check (btrim(email) <> ''),
  constraint invitations_email_shape check (email like '%_@_%.__%'),

  -- 64 hex characters: the length and alphabet of a SHA-256 digest. A short or
  -- non-hex value means something other than a hash was written here.
  constraint invitations_token_hash_shape check (token_hash ~ '^[0-9a-f]{64}$'),

  constraint invitations_expires_after_created check (expires_at > created_at)
);

comment on table public.invitations is
  'A pending or accepted invitation to a team. token_hash is a SHA-256 hash; the token itself is never stored. There is no insert, update or delete policy: only the invite-member and accept-invite functions can write here.';

-- accept-invite looks an invitation up by hash alone, so this is the index that
-- matters most. Unique: two invitations must never share a hash, which would
-- make one token open two invitations.
create unique index invitations_token_hash_key on public.invitations (token_hash);

-- The owner's select rule and invite-member's pending count both filter by
-- team_id.
create index invitations_team_id_idx on public.invitations (team_id);

-- One pending invitation per address per team. A partial index, so an address
-- that was invited and accepted -- or whose invitation expired -- can be invited
-- again, while a second live invitation to the same person is refused by the
-- database rather than only by the function.
create unique index invitations_one_pending_per_email
  on public.invitations (team_id, email)
  where accepted_at is null;

-- Without this line the rule below does nothing at all.
alter table public.invitations enable row level security;

-- One rule, for reading, and it is deliberately narrow: the TEAM'S OWNER, not
-- its members. An invited person's address is not shown to the rest of the team
-- (docs/plan.md, "Email address: never shown to team members"), so a member
-- reading this table would leak exactly what that decision protects.
--
-- (select auth.uid()) is wrapped in a select on purpose: Postgres then works it
-- out once per query instead of once per row.
create policy "Team owners can read their team's invitations"
  on public.invitations
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.teams
      where teams.id = invitations.team_id
        and teams.owner_id = (select auth.uid())
    )
  );

-- No insert, update or delete policy, on purpose. See the header.

-- ---------------------------------------------------------------------------
-- team_members
-- ---------------------------------------------------------------------------

create table public.team_members (
  team_id uuid not null
    references public.teams (id) on delete cascade,

  user_id uuid not null
    references auth.users (id) on delete cascade,

  joined_at timestamptz not null default now(),

  -- One row per person per team, and the pair is the identity of the row. This
  -- is also what makes a second accept of the same invitation fail on the
  -- database rather than quietly adding a duplicate membership.
  primary key (team_id, user_id)
);

comment on table public.team_members is
  'Who belongs to which team. There is no insert, update or delete policy: only the accept-invite function can write here.';

-- The primary key already indexes (team_id, user_id), which serves lookups by
-- team. This covers the other direction -- "which teams am I in?" -- which is
-- what the select rule below and feature 5 both ask.
create index team_members_user_id_idx on public.team_members (user_id);

alter table public.team_members enable row level security;

-- A person reads their own membership rows and nobody else's. Note what this
-- deliberately does NOT grant: it does not let a member list who else is in the
-- team. That needs its own decision, and its own policy, when a feature asks
-- for it.
create policy "People can read their own team membership"
  on public.team_members
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

-- No insert, update or delete policy, on purpose. See the header.
