-- Daily limits on what costs money: usage_counts, and the one function that
-- counts. docs/plan.md, "Daily limits on what costs money", added 2026-10-08
-- with the owner's nine decisions already in it.
--
-- "A count of how many times each person used each limited feature on each day,
-- kept in this project's own database in a table called `usage_counts`, and a
-- refusal once that count has reached the day's limit."
--
-- THIS MIGRATION IS THE DATABASE CHANGE ALONE (issue #220). It adds one table
-- and one function. NOTHING CALLS THE FUNCTION YET: suggest-subtasks and
-- invite-member are not touched by this change and keep behaving exactly as they
-- do today, there is no supabase/functions/_shared/limits.ts in this change, and
-- no screen and no workflow is altered. Counting at the two call sites is the
-- next issue, and until it lands this table stays empty and nothing is limited.
--
-- EXPAND ONLY. One new table and one new function; no existing table, column,
-- constraint, index, policy, trigger, function or grant is altered or dropped.
--
-- DO NOT EDIT THIS FILE once it has been applied anywhere. A migration is
-- applied once; editing an applied one leaves the repository and every database
-- that has already run it silently disagreeing, and the edit reaches none of
-- them. To change any of this, add a new migration.
--
-- Where this migration has been applied is recorded in docs/environments.md and
-- evidence/, not here -- a status note kept in this file goes stale without
-- anyone noticing. On the day it was written it had been applied NOWHERE:
-- not local, not staging, not production.
--
-- ---------------------------------------------------------------------------
-- THE SHAPE, AND THE ONE THING THAT DECIDES IT
-- ---------------------------------------------------------------------------
--
-- Two calls at the same moment must not both pass a limit with room for one.
-- That sentence is why there is a function here at all, and why the counting is
-- ONE statement rather than a read followed by a write. docs/plan.md:
--
--   "This replaces the per-instance 'one call at a time' lock as the real
--    control ... it is a `Set` of user IDs in one isolate's memory, so two asks
--    from one person that land on two isolates both proceed ... A count in a
--    table is the control, because every isolate reads the same row."
--
-- A server function that read the count, compared it with the limit and then
-- wrote would have exactly the fault it was added to fix, moved from one
-- isolate's memory into two statements. So the decision -- the comparison with
-- the limit -- happens inside the statement that does the increment, where
-- Postgres holds the row, and the server function is told only yes or no.
--
-- evidence/build-it-22-usage-counts.md section 5 is a run of the other way
-- round, read-then-write, letting 20 of 20 through a limit of 2.
--
-- ---------------------------------------------------------------------------
-- WHAT service_role GETS, WHICH IS A CORRECTION TO TWO DOCUMENTS
-- ---------------------------------------------------------------------------
--
-- docs/architecture.md said, when it was written on 2026-10-08 before any code:
-- "`service_role` needs select, insert, update and delete" on this table. With
-- the single counting function this migration builds, IT NEEDS NONE OF THOSE.
-- It gets EXECUTE on the function and no privilege at all on the table. The
-- owner's correction, 8 October 2026, and this pull request changes that line
-- and the matching sentence in docs/plan.md.
--
-- Why it is the better shape, in one sentence each:
--
--   * the function is the ONLY way to count, so the limit cannot be got around
--     by a server function writing the table directly -- not by mistake, and
--     not by a later feature that finds it convenient;
--   * the delete that enforces the 7-day window is inside the function too, so
--     no role outside it may delete a count, and the retention cannot be skipped
--     by anybody who merely has the key;
--   * a role that cannot SELECT the table cannot read which days somebody used
--     this app, which is the one fact these rows hold.
--
-- The function is `security definer` precisely so that this works: it runs as
-- its owner (postgres, which applied this migration and owns the table), so the
-- caller needs no privilege on the table -- only the right to call it.

-- ---------------------------------------------------------------------------
-- 1. usage_counts -- one row per person, per feature, per day
-- ---------------------------------------------------------------------------
--
-- FOUR COLUMNS, AND THE ABSENCES ARE THE DESIGN. docs/plan.md: "the person's
-- ID, the feature, the day, and the count. Four values. Nothing about which
-- task and nothing about which address: not a task id, not a title, not an
-- invited person's email, not a team, not a time of day, not whether the use
-- succeeded. A row says 'this person used this feature this many times on this
-- day' and is incapable of saying more."
--
-- There is deliberately no created_at and no updated_at, which every other
-- table here has. A timestamp would say what time of day somebody was active,
-- and the plan's "Collecting less -- added 2026-10-08" list rules it out by
-- name: "no time of day -- so the count cannot be read backwards into what
-- somebody was doing, only how often."

create table public.usage_counts (
  -- The person. docs/plan.md: "The rows are keyed by the person's ID and go
  -- when the account goes." on delete cascade is what makes that true in the
  -- database rather than in an intention -- the same line account_status and
  -- profiles use.
  user_id uuid not null
    references auth.users (id) on delete cascade,

  -- WHICH LIMITED THING. A short fixed word, never free text: the constraint
  -- below is what makes that true of every row rather than only the ones the
  -- function wrote.
  feature text not null,

  -- date, NOT timestamptz, and that is the column that keeps "no time of day"
  -- true. A date cannot record a moment even if somebody wanted it to.
  --
  -- It is a UTC date, and nothing in this table says so -- the function below
  -- is the only thing that writes this column, and it works the date out with
  -- `(now() at time zone 'utc')::date` rather than taking one from a caller.
  -- docs/plan.md: "The day is a UTC day ... Not the person's local day, because
  -- the app does not know what that is."
  day date not null,

  -- HOW MANY TIMES. A count, not a log: docs/plan.md's "A count, not a log. One
  -- row per person, per feature, per day, holding a number. Not a row per use,
  -- which would be a timestamped record of each time somebody pressed a button,
  -- and would be the request logging 'Logs: we add none of our own' rules out."
  --
  -- Named `used` rather than `count`, which is a function name in every SQL
  -- statement anybody will ever write against this table.
  used integer not null,

  -- ONE ROW PER PERSON, PER FEATURE, PER DAY, and the primary key is what makes
  -- a second row for the same three values unrepresentable. It is also what the
  -- counting statement below conflicts on, so this line is not merely tidiness:
  -- `on conflict (user_id, feature, day)` needs exactly this unique constraint
  -- to exist, and a use is therefore an increment rather than an insert.
  primary key (user_id, feature, day)
);

comment on table public.usage_counts is
  'One row per person, per limited feature, per UTC day, holding how many times they used it that day. Written by public.count_daily_use() and by nothing else. No policy and no table privilege for any role, so nothing in the app -- not even a server function, and not even the person the row is about -- can read or write it; the operator reads it in the dashboard. Rows older than the 7-day window are removed by the same function that counts. See docs/plan.md, "Daily limits on what costs money".';

comment on column public.usage_counts.user_id is
  'The auth.users id of the person who used the feature. on delete cascade: the count goes with the account.';

comment on column public.usage_counts.feature is
  'Which limited feature: ai_suggestions or invitations, and nothing else -- usage_counts_feature_allowed is the fixed list. Adding a feature needs a new migration, on purpose.';

comment on column public.usage_counts.day is
  'The UTC day the uses happened on. A date, not a timestamp, so the row cannot say what time of day anybody was active. Worked out by public.count_daily_use(), never supplied by a caller.';

comment on column public.usage_counts.used is
  'How many times, that day. Counted before the paid call and never given back, so it can be higher than the number of requests that reached anybody and never lower (docs/plan.md).';

-- THE FIXED LIST, and why these two. One per thing in this app that spends
-- money when somebody presses a button, which is docs/architecture.md's
-- "Which functions write it: the two that spend money, and nothing else":
--
--   ai_suggestions  one metered request to Anthropic, from suggest-subtasks
--   invitations     one email to the email service, from invite-member --
--                   including a retry, which sends a second one
--
-- A check constraint rather than a Postgres enum, for the reason
-- 20261006095847_invitation_status.sql gives: every other restricted value in
-- this schema is a check constraint, and an enum's values cannot be removed
-- later without recreating the type.
--
-- ADDING A FEATURE NEEDS A NEW MIGRATION, which is the point of a fixed list.
-- A feature word is also the key the counting function is called with, so a
-- typo at a call site -- 'ai_suggestion', 'invite' -- is refused by the database
-- rather than quietly counted in a fourth bucket that no limit watches. The
-- function below turns that refusal into an error, and an error at the call site
-- means the paid call does not happen: fail closed.
--
-- The column is NOT NULL, so this check has no null to fall through: it never
-- evaluates to unknown, and "unknown" is how a check constraint silently accepts
-- a row it was written to refuse.
alter table public.usage_counts
  add constraint usage_counts_feature_allowed
  check (feature in ('ai_suggestions', 'invitations'));

-- A ROW EXISTS BECAUSE SOMETHING WAS USED, so the smallest honest value is 1.
-- `used >= 1` rather than `>= 0`: a zero row would be a record that somebody did
-- NOT use a feature on a day, which is a fact about a person this table has no
-- business holding, and it is also unreachable -- the function inserts 1 or
-- increments, never 0.
--
-- There is no upper bound on purpose. The limit is not a property of the table:
-- it is passed in by the caller from supabase/functions/_shared/limits.ts (the
-- next issue), so a limit changed in that one file does not need a migration
-- here. A constraint naming 20 would quietly become a second place to change.
alter table public.usage_counts
  add constraint usage_counts_used_is_a_use
  check (used >= 1);

-- NO INDEX BEYOND THE PRIMARY KEY. Two questions are ever asked of this table,
-- and the primary key answers both: "this person, this feature, today" is an
-- exact match on all three columns, and "this person's rows older than the
-- window" is a range scan on the key's leading column.

-- Without this line, the absence of policies below would mean nothing at all.
alter table public.usage_counts enable row level security;

-- AND NO POLICIES, on purpose, exactly as 20261004114313_suspend_accounts.sql
-- leaves account_status. Row-level security refuses what no policy allows, so
-- this is the whole of the app's access to this table: none.
--
-- That is the second of two locks, and it is the weaker one. The first is the
-- revokes below. Privileges are checked BEFORE row-level security, so a caller
-- without the privilege never reaches the question of which rows it may see --
-- which is why the revokes, and not this line, are what make the table
-- unreachable. This line is here so that a future `grant` by accident does not
-- immediately open the table as well.
--
-- SUPABASE'S SECURITY ADVISOR REPORTS THIS AS `rls_enabled_no_policy`, and that
-- is the table working as designed rather than a finding to fix.
-- evidence/production-log.md records the same notice being accepted for
-- account_status on 4 October 2026.

-- ---------------------------------------------------------------------------
-- 2. Who may reach the table: nobody
-- ---------------------------------------------------------------------------
--
-- WHAT A NEW TABLE GETS BY DEFAULT TODAY, which is the reason this section
-- exists. Supabase grants select, insert, update and delete on every table in
-- the public schema to anon, authenticated and service_role -- its changelog of
-- 28 April 2026, "Breaking Change: Tables not exposed to Data and GraphQL API
-- automatically", says of an existing project: "select, insert, update, and
-- delete are granted to every table in the `public` schema to the `anon`,
-- `authenticated` and `service_role` roles."
--
-- So this table arrives readable and writable by the app, and the lines below
-- are what close it. Not a precaution against a hypothetical: without them any
-- signed-in person could read which days anybody used this app, and -- worse for
-- the thing this table is for -- could DELETE their own count and start the day
-- again, which would make the limit decorative.
--
-- WHY EVERY LINE IS WRITTEN OUT, including ones that are no-ops in one direction
-- or the other. Issue #220: "Write every grant and revoke explicitly. Supabase
-- applies 'new public tables are not exposed by default' to existing projects on
-- 30 October 2026 (changelog 45329), and CI's CLI already behaves that way
-- locally; this table must behave the same before and after that date."
--
--   BEFORE that date, on a project that still has the old defaults: the revokes
--   below take away four privileges per role that Supabase granted.
--   AFTER it, on a project with the new defaults: there is nothing to take away
--   and every revoke is a no-op that succeeds.
--
-- Either way the table ends with no privilege for any of the three roles, which
-- is the only thing this section is trying to be true. Both halves were run:
-- evidence/build-it-22-usage-counts.md section 4 builds two databases, one with
-- the old defaults and one with the new, applies the same ten migrations to each,
-- and reads has_table_privilege back from both -- all false in both.
--
-- PUBLIC IS NAMED TOO. A new table grants PUBLIC nothing, so this is
-- belt-and-braces rather than a fix -- and it is written because the issue asks
-- for every revoke explicitly, and because a reader should not have to know what
-- a default does in order to see that nothing is left open.
revoke all on table public.usage_counts from public;
revoke all on table public.usage_counts from anon;
revoke all on table public.usage_counts from authenticated;

-- SERVICE_ROLE IS REVOKED WITH THE OTHER TWO, AND NOTHING IS GIVEN BACK. This is
-- the line docs/architecture.md and docs/plan.md are corrected for, and the one
-- place this table differs from account_status -- which keeps `select` for
-- service_role because the three server functions read it directly.
--
-- Nothing here is read directly. The two functions that count do it by calling
-- public.count_daily_use(), which runs as its owner, so service_role needs no
-- select, no insert, no update and -- the one the correction turns on -- no
-- delete. docs/architecture.md said delete was needed "because of the 7-day
-- decision": that is true of whatever does the deleting, and what does the
-- deleting is the function, not the role.
--
-- WHAT THIS BUYS, stated plainly because it is the whole reason to prefer it: a
-- server function holding the service-role key cannot add to a count, cannot
-- reset one to start somebody's day again, cannot delete the window early, and
-- cannot read which days a person used this app. The only thing it can do is ask
-- for one use and be told yes or no.
--
-- IF A LATER FEATURE REALLY NEEDS A DIRECT READ -- an operator screen, say -- it
-- grants what it needs then, in its own migration, with a reason, and it should
-- expect to update docs/plan.md first, because the plan's "Who can see it: no
-- app user, not even the person whose count it is" is what this line enforces.
revoke all on table public.usage_counts from service_role;

-- ---------------------------------------------------------------------------
-- 3. count_daily_use() -- the only way to count, and the only way to be refused
-- ---------------------------------------------------------------------------
--
-- "It takes the person's ID, the feature and the limit; in ONE statement it adds
-- one to today's count only if the count is below the limit, and says whether
-- the use is allowed." (issue #220)
--
-- WHO IS ASKING IS AN ARGUMENT HERE, and that is the opposite of is_active() and
-- my_ai_suggestions(), which read auth.uid() inside their own bodies so they can
-- never be asked about somebody else. The reason is that there is no session to
-- read: the caller is a server function on an admin connection, where auth.uid()
-- is null for everybody. 20261004114313_suspend_accounts.sql spells out the trap
-- in full -- a server function calling is_active() would refuse every caller and
-- would do it without an error -- and the same shape applies here, so the user id
-- is passed in, exactly as the three server functions pass one when they read
-- account_status.
--
-- THE CONSEQUENCE, AND IT IS NOT A HOLE: anybody who can call this can count
-- against anybody's id. Only service_role can call it (section 4), which is a
-- role no browser ever holds; a role that can already act for anybody is not
-- made more powerful by being able to spend one of their twenty. The direction
-- that would matter -- counting somebody DOWN so they are refused -- is a
-- denial-of-service by a holder of the service-role key, who has larger
-- problems available to them.
--
-- THE LIMIT IS AN ARGUMENT, NOT A CONSTANT HERE. docs/plan.md: "Both numbers
-- live in one config file: supabase/functions/_shared/limits.ts ... Not spelled
-- at a call site and not in two places." A number written into this function
-- would be a third place, and changing it would need a migration.
--
-- security definer, so it runs as the role that owns it -- postgres, which
-- applied this migration and owns the table -- rather than as the caller. That
-- is the point of the whole file: the caller has no privilege on usage_counts at
-- all, so the counting cannot be done as the caller, and the table stays closed
-- to everything except this one door. Row-level security does not apply to the
-- table's owner either, so the "no policies" above does not stand in its way.
--
-- Running as the owner is why the guards below matter, and the reasoning is
-- 20261002122203_team_rules.sql's, unchanged:
--
--   set search_path = ''  so no schema is searched implicitly. A function
--                         running with more rights than its caller must not
--                         resolve a name through a path somebody else can
--                         change, or it can be made to call their function
--                         instead of the one written here.
--   schema-qualified      the consequence: public.usage_counts must be written
--                         in full or it does not resolve at all. now() still
--                         resolves, because pg_catalog is searched first
--                         whatever the path says.
--
-- NOT stable and not immutable: it writes. The default, volatile, is correct and
-- is left unwritten the way plpgsql functions in this schema leave it.
create function public.count_daily_use(
  p_user_id uuid,
  p_feature text,
  p_limit integer
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  -- THE DAY IS WORKED OUT HERE AND NOWHERE ELSE. `now() at time zone 'utc'`
  -- turns the transaction's timestamp into UTC wall-clock time, and ::date takes
  -- the date off it. NOT current_date, which is the date in whatever the server's
  -- TimeZone setting happens to be -- a session that did `set timezone` could
  -- otherwise shift which day it was counting against.
  --
  -- It is read once and used for both statements below, so the increment and the
  -- removal cannot disagree about what day it is even if the call spans midnight.
  l_today date := (now() at time zone 'utc')::date;

  -- null unless the statement below returned a row. Never returned as null:
  -- see the coalesce at the end.
  l_allowed boolean;
begin
  -- FAIL CLOSED ON A MISSING ARGUMENT. A null user id, feature or limit is a
  -- caller with a bug, and "no" is the answer that cannot cost money. Without
  -- this, a null user id would raise a not-null violation -- also a refusal, by
  -- way of an error the caller has to remember to treat as one.
  --
  -- A null feature or a null limit would already come out false below (the
  -- insert's `where` and the update's `where` both go unknown), so this line is
  -- what makes all three the same answer, arrived at the same way.
  if p_user_id is null or p_feature is null or p_limit is null then
    return false;
  end if;

  -- ---------------------------------------------------------------------
  -- ONE STATEMENT. The whole control is here.
  -- ---------------------------------------------------------------------
  --
  -- Read it as three cases:
  --
  --   no row for today yet   the insert succeeds with used = 1, a row comes
  --                          back, and the use is allowed.
  --   a row, used < limit    the insert conflicts, DO UPDATE's `where` holds,
  --                          used becomes used + 1, a row comes back, allowed.
  --   a row, used >= limit   the insert conflicts, DO UPDATE's `where` fails,
  --                          NOTHING is written and NO row comes back. Refused.
  --
  -- WHY THIS IS SAFE WITH TWENTY CALLERS AT ONCE, which is the requirement the
  -- whole function exists for. `insert ... on conflict do update` is Postgres's
  -- own atomic upsert: the second caller to arrive at the same key waits for the
  -- first to finish, then re-reads the row it is about to update and evaluates
  -- DO UPDATE's `where` against that NEW version. So the twentieth caller
  -- compares the limit with the count the other nineteen left behind, not with
  -- the one it read before they ran. A read followed by a write cannot do this:
  -- the gap between the two is where twenty callers all see room for one.
  --
  -- Measured rather than argued: evidence/build-it-22-usage-counts.md section 5
  -- fires 20 simultaneous calls at a limit of 2, ten rounds over, and 2 are
  -- allowed every time -- and the same section does it again with the obvious
  -- read-then-write version, which lets all 20 through.
  --
  -- `where p_limit > 0` ON THE INSERT, which looks odd and is load-bearing. With
  -- a limit of 0 or less there is no conflict to fall through to, so without
  -- this the first call of the day would insert used = 1 and be allowed -- a
  -- limit of zero that permits one. `select ... where false` returns no rows, so
  -- nothing is inserted and nothing comes back. A limit of 0 therefore refuses
  -- everybody, which is what a limit of 0 should mean, and what somebody
  -- switching a feature off in limits.ts would expect it to mean.
  --
  -- AN UNKNOWN FEATURE IS AN ERROR, NOT A QUIET FOURTH BUCKET.
  -- usage_counts_feature_allowed refuses it, the error leaves this function, and
  -- the caller's own refusal path is what stops the paid call. That is the
  -- fail-closed direction, and it is why the fixed list is in the database
  -- rather than only in TypeScript.
  insert into public.usage_counts as uc (user_id, feature, day, used)
  select p_user_id, p_feature, l_today, 1
  where p_limit > 0
  on conflict (user_id, feature, day) do update
    set used = uc.used + 1
    where uc.used < p_limit
  returning true
  into l_allowed;

  -- ---------------------------------------------------------------------
  -- THE 7-DAY WINDOW, enforced by code on a path that is already writing
  -- ---------------------------------------------------------------------
  --
  -- docs/plan.md, decided by the owner on 2026-10-08: "7 days, removed by the
  -- same statement that does the counting ... The removal is in code, not in a
  -- routine, and that is the half of the decision that matters ... it needs no
  -- scheduler, no new dependency and no second thing for anybody to remember --
  -- and it cannot drift, because it runs on every use. A retention period that
  -- depends on somebody doing it is not a retention period; it is a permanent
  -- record wearing a window's label."
  --
  -- THIS PERSON'S ROWS ONLY. `where user_id = p_user_id` is not an optimisation:
  -- a statement that swept the whole table would make every count a write
  -- against rows belonging to other people, and twenty callers at once would be
  -- deleting each other's rows while holding each other's locks. Each caller
  -- tidies up after itself and nobody else.
  --
  -- WHICH MAKES THE WINDOW SELF-ENFORCING BUT NOT UNIVERSAL, and that is worth
  -- knowing rather than discovering: a person who stops using the app keeps the
  -- rows they had until they come back, because nothing else ever runs. At one
  -- row per person per feature per day, with two features and about six people,
  -- that is a handful of rows holding a number each -- and the alternative is the
  -- scheduler the plan declined. The operator can delete them by hand if it ever
  -- matters.
  --
  -- WHERE THE BOUNDARY IS DRAWN, because "7 days" has two readings and this one
  -- had to be picked. `day <= l_today - 7` removes the row dated exactly seven
  -- days ago, so what survives is TODAY AND THE SIX DAYS BEFORE IT: seven dates,
  -- never eight. The other reading -- "older than 7 days", which keeps a row
  -- aged exactly 7 -- would hold eight dates under a heading that says seven.
  -- The plan says "How long it is kept: 7 days" and its whole bias is to collect
  -- less, so seven dates it is. It is one character to change if the owner wants
  -- the other reading, and evidence/build-it-22-usage-counts.md section 8 shows
  -- the boundary row by row.
  --
  -- It runs AFTER the counting and in the same transaction, so a count and its
  -- tidy-up are one atomic thing: if the delete fails, the count is rolled back
  -- with it and the caller is told nothing was counted, which is the safe way for
  -- that pair to fail.
  --
  -- It also runs when the answer was NO, which is deliberate: a person at their
  -- limit is still a person whose old rows should go, and the alternative is a
  -- window that stops being enforced for exactly the people who use the app
  -- most.
  delete from public.usage_counts
  where user_id = p_user_id
    and day <= l_today - 7;

  -- NEVER NULL. `returning true into l_allowed` leaves the variable null when
  -- the statement wrote nothing, and null is the answer a caller is most likely
  -- to get wrong -- `if (allowed)` and `if (!refused)` disagree about it. So the
  -- function has exactly two answers, and "nothing was written" is false.
  return coalesce(l_allowed, false);
end;
$$;

comment on function public.count_daily_use(uuid, text, integer) is
  'Counts one use of a limited feature for one person on today''s UTC day, and returns whether it was allowed: true when the count was below the limit and has been increased, false when it had already reached it. The check and the increment are ONE statement, so two simultaneous calls cannot both pass a limit with room for one. Also removes that person''s rows dated seven or more days ago, so the 7-day window is enforced by the counting itself rather than by a scheduler. Returns false -- never null -- for a null argument or a limit of zero or less; raises on a feature outside usage_counts_feature_allowed, which the caller must treat as a refusal. security definer, because no role has any privilege on public.usage_counts. See docs/plan.md, "Daily limits on what costs money".';

-- ---------------------------------------------------------------------------
-- 4. Who may call it: the server functions' role, and nobody else
-- ---------------------------------------------------------------------------
--
-- Postgres grants execute on a new function to PUBLIC automatically, and a
-- function in the public schema is published by PostgREST as an RPC endpoint --
-- so "PUBLIC" here means anybody who can reach the API with the publishable key.
-- Revoking from PUBLIC closes that door before it is ever open.
--
-- anon and authenticated are named SEPARATELY, and that is not belt-and-braces:
-- Supabase grants execute on new functions to anon, authenticated and
-- service_role BY NAME as well, which are different grants from the one PUBLIC
-- holds, and revoking from PUBLIC does not remove them. These two lines are what
-- actually stop a browser calling this.
--
-- WHAT A SIGNED-IN CALLER COULD DO WITH IT IF THEY COULD CALL IT, which is why
-- this is the most important revoke in the file: `select
-- public.count_daily_use('<their own id>', 'ai_suggestions', 999999)` passes its
-- own limit, so the caller would choose the limit. The function cannot defend
-- against that -- the limit has to be an argument (section 3) -- so the defence
-- is that no client role may call it at all. A limit enforced by a number the
-- browser hands you is not enforced.
revoke execute on function public.count_daily_use(uuid, text, integer) from public;
revoke execute on function public.count_daily_use(uuid, text, integer) from anon;
revoke execute on function public.count_daily_use(uuid, text, integer) from authenticated;

-- AND GRANTED, EXPLICITLY, to the one role that needs it. Supabase's default
-- would have given service_role execute anyway -- 20261004114313's own comment
-- records that happening to is_active() -- so on a project with today's defaults
-- this line grants nothing new.
--
-- It is written because that default is going away for new objects on 30 October
-- 2026 (changelog 45329, issue #130), and a permission that exists only because
-- of a default nobody wrote is a permission nobody can see. Without this line
-- the next issue's counting would work on both projects today and stop working
-- on a project created after that date, and the only symptom would be a 42501
-- from inside suggest-subtasks. An explicit grant is not a default and is not
-- withdrawn by a change to defaults.
--
-- ONE RIGHT, ONE ROLE, ONE DOOR: this is the whole of anybody's access to
-- usage_counts. Section 2 left no table privilege for any role, so there is no
-- second way in for anything holding the service-role key.
grant execute on function public.count_daily_use(uuid, text, integer) to service_role;

-- ---------------------------------------------------------------------------
-- 5. The 30 October 2026 change, and why this table behaves the same either way
-- ---------------------------------------------------------------------------
--
-- Supabase applies "new public tables are not exposed by default" to existing
-- projects on 30 October 2026 (changelog 45329); issue #130 holds that question
-- for this repository, and issue #220 asks that this table behave the same
-- before and after.
--
-- IT DOES, AND THE REASON IS THE DIRECTION EVERY LINE ABOVE POINTS IN. The
-- change alters DEFAULT privileges -- #130's sandbox settled that "the old table
-- keeps its grants, the new one has none" -- so the only things it can affect are
-- privileges this file RESTS ON rather than writes down. This file rests on none:
--
--   * every table privilege is revoked by name, for all three roles and PUBLIC.
--     Before the date those revokes remove something; after it they remove
--     nothing. Either way nothing is left.
--   * every function privilege is either revoked by name (PUBLIC, anon,
--     authenticated) or granted by name (service_role). The one the next issue
--     depends on is the grant, and it is written.
--
-- So there is exactly one way to reach this table on either side of that date:
-- service_role calling public.count_daily_use(). Both sides were built and read
-- back -- evidence/build-it-22-usage-counts.md section 4, two databases differing
-- only in their default privileges, with identical has_table_privilege and
-- has_function_privilege output.
--
-- ---------------------------------------------------------------------------
-- What the NEXT issue must do, and what this migration cannot
-- ---------------------------------------------------------------------------
--
-- NOTHING IS LIMITED YET. This file adds the control; it does not connect it.
-- Until the next issue lands, the only thing between a retry loop and a bill is
-- Anthropic's 5-dollar spend limit and the email service's own quota, exactly as
-- docs/costs.md says today.
--
-- What has to happen there, from docs/plan.md and docs/architecture.md:
--
--   supabase/functions/_shared/limits.ts   the two numbers, 20 and 20, in one
--                                          file read by both functions.
--   suggest-subtasks                       after the door checks and the consent
--                                          check, IMMEDIATELY BEFORE the call to
--                                          the AI service.
--   invite-member                          after the door checks and the team's
--                                          20-pending check, IMMEDIATELY BEFORE
--                                          the send -- and a retry counts,
--                                          because it sends a second email.
--
-- Both call this function and refuse on false with the plan's own sentence,
-- "You've reached today's limit. It resets tomorrow.", and its own code -- not
-- one of the twelve fixed failure codes, for the reason the plan gives.
--
-- AND BOTH MUST TREAT AN ERROR FROM THIS FUNCTION AS A REFUSAL. A failed count is
-- not permission to spend money, the same way round as create-team counting teams
-- where "an unknown is not a zero".
