-- AI suggestions, the consent setting: docs/plan.md, "AI suggestions -- the
-- consent setting".
--
-- "A setting called AI suggestions, on each person's profile. Off for everyone
-- -- including every account that already exists on the day it arrives, so
-- nobody is opted in by a migration and a person who never touches it has never
-- sent anything. Only that person can switch it, and only for themselves."
--
-- THIS MIGRATION IS THE DATABASE CHANGE ALONE (issue #206). It adds two
-- columns, a trigger, a reader function and the privileges that decide who may
-- reach any of it. Nothing reads or writes the setting yet: suggest-subtasks is
-- not touched by this change and keeps behaving exactly as it does today, and
-- there is no screen. The function check and the screen are the next issues.
--
-- EXPAND ONLY. Both columns are new; one has a default and the other is
-- nullable, so the single insert the app makes -- web/src/app/teams/actions.ts
-- naming user_id and display_name and nothing else -- still succeeds unchanged,
-- as does its update of display_name. No existing column, constraint, index or
-- policy is altered or dropped. The four policies on public.profiles are left
-- exactly as they were.
--
-- DO NOT EDIT THIS FILE once it has been applied anywhere. A migration is
-- applied once; editing an applied one leaves the repository and every database
-- that has already run it silently disagreeing, and the edit reaches none of
-- them. To change any of this, add a new migration.
--
-- Where this migration has been applied is recorded in docs/environments.md and
-- evidence/, not here -- a status note kept in this file goes stale without
-- anyone noticing.
--
-- ---------------------------------------------------------------------------
-- THE DECISION THAT SHAPES THE WHOLE FILE, AND WHO MADE IT
-- ---------------------------------------------------------------------------
--
-- Issue #206 asks who, other than the person, can read the setting under the
-- rules as they already stand -- and says to stop and ask if anybody can.
-- Somebody can. public.profiles has a select policy reading "You can read your
-- own profile and your team mates' profiles", so every non-suspended person who
-- shares a team with you reads your whole row. Read back from a sandbox built
-- from the eight migrations before this one, as the owner of a team Carol
-- belongs to:
--
--   set role authenticated; set sandbox.uid = '1111...';   -- Alice
--   select user_id, display_name from public.profiles where user_id = '3333...';
--   -> 1 row
--
-- docs/plan.md's appendix says of this setting: "Who can see it: the person
-- whose setting it is; owner". A column on this table is therefore NOT private
-- by default, and leaving it so would have contradicted the plan.
--
-- THE OWNER'S DECISION, 7 OCTOBER 2026, asked and answered before this file was
-- written: hide the two columns from the app's two client roles at the PRIVILEGE
-- layer, and give the person a function that returns their own value. Row-level
-- security cannot do this job -- a policy chooses rows, not columns, and the one
-- select policy here is the same policy that makes a team's members list show
-- nicknames. Narrowing it would break the members list, which "expand only"
-- forbids. Column privileges can choose columns, so that is the layer used.
--
-- Two alternatives were put to the owner and not chosen, recorded so the
-- question is not re-argued from scratch:
--
--   * accept the team-mate read. Simplest, and plainly expand-only, but it
--     needs docs/plan.md changed first (rule 9), because the appendix says only
--     the person and the owner can see it;
--   * a separate one-row-per-person table, where an own-row-only select policy
--     would answer the question directly. Cleaner at the row layer, but it goes
--     past both issue #206 ("one new migration on profiles") and the plan,
--     which says profiles with a proposed column.

-- ---------------------------------------------------------------------------
-- 1. The two columns
-- ---------------------------------------------------------------------------
--
-- boolean not null default false, so there is no third state to reason about
-- and no migration opts anybody in. "Off for everyone -- including every account
-- that already exists on the day it arrives" is what the default achieves:
-- adding a column with a default does not rewrite the table on PostgreSQL 11
-- and later, the default is recorded in the catalogue and applied on read, and
-- every existing row therefore reads false without a single row being written.
--
-- There is deliberately no backfill statement. 20261006095847_invitation_status
-- needed one because its existing rows had to be called something other than
-- the default; here the default IS the answer the plan asks for.
alter table public.profiles
  add column ai_suggestions_enabled boolean not null default false;

-- NULLABLE, and null means "nobody has ever changed it". That is a real third
-- state here, unlike invitations.status, and the alternative states a falsehood:
-- `not null default now()` would record that every account in the database
-- changed their AI-suggestions setting at the moment this migration ran, which
-- is the opposite of "a person who never touches it has never sent anything".
--
-- Nothing may put a value in this column. Not the person, not a server
-- function, not another signed-in caller: it is stamped by the trigger in
-- section 2 and by nothing else. Two locks do that, and they are at different
-- layers -- the privileges in section 4 refuse a client role that names this
-- column at all, and the trigger refuses every caller, including the operator
-- and service_role, who hands it a value.
alter table public.profiles
  add column ai_suggestions_changed_at timestamptz;

comment on column public.profiles.ai_suggestions_enabled is
  'Whether this person has switched AI suggestions on. Off for every existing and every new row. Only the person can change it, and only on their own row: the existing own-row update policy decides the row, and a column-level update grant decides the column. No server function can change it either -- service_role has select on this column and no insert or update. No client role may READ it, so a team mate cannot learn it through the existing team-mate select policy; the person reads their own value through public.my_ai_suggestions().';

comment on column public.profiles.ai_suggestions_changed_at is
  'When ai_suggestions_enabled last changed, stamped by the trigger profiles_stamp_ai_suggestions and settable by nobody. Null means it has never been changed, which is not the same as off at an unknown time. No client role may read or write it.';

-- WHAT THIS MAKES UNREPRESENTABLE: a setting that is on with no record of when
-- it was switched on. The trigger below maintains that, and this constraint is
-- what makes it true of every row rather than only the ones the trigger saw --
-- added to a populated table, so applying this migration also checks it against
-- every row that already exists, and every one of them holds the default false.
--
-- It does NOT say the reverse. On, then off again, leaves a timestamp with the
-- setting false, which is correct: the setting was changed, and that is when.
alter table public.profiles
  add constraint profiles_ai_suggestions_on_is_dated
  check (ai_suggestions_enabled = false or ai_suggestions_changed_at is not null);

-- ---------------------------------------------------------------------------
-- 2. The trigger: the database stamps the time, and refuses anybody who tries
-- ---------------------------------------------------------------------------
--
-- Issue #206: "When it was last changed, set by the database itself, never by
-- the caller", and "Nothing may let a caller set the last changed value".
--
-- IT RAISES RATHER THAN SILENTLY OVERWRITING, following
-- tasks_enforce_column_rules in 20261002133637_tasks_join_teams.sql, which
-- raises 42501 when a caller tries to change tasks.created_at. Quietly
-- discarding a forged value would leave a caller believing it took, and would
-- leave nothing in a log to say somebody tried.
--
-- NOT security definer, and that is deliberate rather than an omission. Every
-- other function in this schema that needs it needs it because it reads a table
-- the caller may not read -- is_team_member reads team_members, is_active reads
-- account_status, tasks_enforce_column_rules reads teams. This one reads no
-- table at all: it compares OLD with NEW and calls now(). A function that needs
-- no extra rights should not hold any.
--
--   set search_path = ''  so no schema is searched implicitly. now() still
--                         resolves, because pg_catalog is searched first
--                         whatever the path says.
create function public.profiles_stamp_ai_suggestions()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    -- A new row has never been changed, so there is nothing to stamp and
    -- nothing a caller may supply. The app's own insert names user_id and
    -- display_name only, so it passes here untouched.
    if new.ai_suggestions_changed_at is not null then
      raise exception 'ai_suggestions_changed_at is set by the database, never by a caller.'
        using errcode = '42501';
    end if;

    -- A row created already switched on is not something the app can make --
    -- section 4 grants no client role INSERT on that column, so an insert
    -- naming it is refused before this trigger runs. The operator and
    -- service_role can, and if they do, the moment is recorded rather than left
    -- blank, which is also what profiles_ai_suggestions_on_is_dated requires.
    if new.ai_suggestions_enabled then
      new.ai_suggestions_changed_at := now();
    end if;

    return new;
  end if;

  -- From here on this is an update, so old is populated.

  -- THE FORGERY CHECK COMES FIRST, before the stamp, so that handing this
  -- column a value is refused whether or not the setting itself moved. In a
  -- BEFORE row trigger an unnamed column arrives in NEW holding its old value,
  -- so an ordinary display-name update reaches this line with the two equal and
  -- passes through: that is what keeps this migration expand-only.
  if new.ai_suggestions_changed_at is distinct from old.ai_suggestions_changed_at then
    raise exception 'ai_suggestions_changed_at is set by the database, never by a caller.'
      using errcode = '42501';
  end if;

  if new.ai_suggestions_enabled is distinct from old.ai_suggestions_enabled then
    new.ai_suggestions_changed_at := now();
  end if;

  return new;
end;
$$;

comment on function public.profiles_stamp_ai_suggestions() is
  'Trigger on public.profiles. Stamps ai_suggestions_changed_at with now() when ai_suggestions_enabled changes, and raises 42501 (insufficient_privilege) if any caller -- including the operator and service_role -- supplies a value for it. An update that does not touch the setting passes through unchanged, which is what keeps the existing display-name writes working.';

-- EXECUTE on a trigger function is not checked when the trigger fires, and a
-- trigger function cannot be called directly, so the default PUBLIC grant
-- serves nothing. Narrowed for consistency with is_team_member, is_active and
-- tasks_enforce_column_rules.
revoke execute on function public.profiles_stamp_ai_suggestions() from public;
revoke execute on function public.profiles_stamp_ai_suggestions() from anon;
revoke execute on function public.profiles_stamp_ai_suggestions() from authenticated;
revoke execute on function public.profiles_stamp_ai_suggestions() from service_role;

-- BEFORE, not AFTER: a BEFORE row trigger can change NEW and can refuse the
-- change before the row is written, and this one does both. FOR EACH ROW,
-- because both rules are about one row's columns.
--
-- Not fired on delete, on purpose: there is no delete policy on this table, and
-- nothing about a stamped time decides who may remove a profile.
create trigger profiles_stamp_ai_suggestions
  before insert or update on public.profiles
  for each row
  execute function public.profiles_stamp_ai_suggestions();

-- ---------------------------------------------------------------------------
-- 3. my_ai_suggestions() -- how the person reads their own setting
-- ---------------------------------------------------------------------------
--
-- Section 4 leaves no client role any SELECT on either new column, which closes
-- the team-mate read -- and closes the person's own read with it. This function
-- is how the person gets their own value back, and nobody else's.
--
-- WHO IS ASKING IS NEVER AN ARGUMENT, as with is_team_member and is_active: it
-- reads auth.uid() inside its own body and takes no parameters at all, so there
-- is nothing to pass and no way to ask about somebody else.
--
-- IT ALWAYS RETURNS EXACTLY ONE ROW, which is the whole reason it is written
-- this way rather than as a view or a plain select. docs/plan.md: "If the
-- setting cannot be read, it is off. A failed read is not a yes." Three
-- different nothings all have to come back as off, and a function that returned
-- no rows would hand that decision to whatever is calling it:
--
--   no profile row at all   an account exists with no profile until the person
--                           saves a nickname (there is no trigger on auth.users,
--                           and display_name is not null with no default), so
--                           this is the ordinary state of a new account, not an
--                           error -> false
--   suspended               docs/plan.md: a suspended person reads and changes
--                           nothing -> false
--   signed out              auth.uid() is null -> false
--
-- is_active() answers the last two in one call, and is false for both. coalesce
-- answers the first. So the boolean is total: true or false, never null, and
-- never an empty result.
--
-- changed_at is null in all three cases as well, and null for a person who has
-- simply never changed the setting. That is deliberate: a refused caller is told
-- nothing about the row, not even whether one exists.
--
-- security definer, so it runs as the role that owns it (postgres, which
-- applied this migration) rather than as the caller. That is the point: the
-- caller has no privilege on the two columns, so reading them as the caller
-- would fail with 42501 for everybody, the person included.
--
-- Running as postgres is why the guards below matter, and the reasoning is
-- 20261002122203_team_rules.sql's, unchanged:
--
--   set search_path = ''  so no schema is searched implicitly. A function
--                         running with more rights than its caller must not
--                         resolve a name through a path somebody else can
--                         change, or it can be made to call their function
--                         instead of the one written here.
--   schema-qualified      the consequence: public.is_active(), public.profiles
--                         and auth.uid() must each be written in full or they do
--                         not resolve at all.
--   stable                it reads a table and changes nothing, so Postgres may
--                         work it out once per query rather than once per row.
--
-- IT BYPASSES ROW-LEVEL SECURITY, AND THAT IS WHY is_active() IS IN THE BODY.
-- Running as postgres means the restrictive policy "Suspended accounts are
-- refused everything" is never evaluated for this read. Without the is_active()
-- call a suspended person would get their setting back through this function
-- while being refused everything else -- the quiet kind of hole, where a fourth
-- door ignores a rule the other three keep.
create function public.my_ai_suggestions()
returns table (enabled boolean, changed_at timestamptz)
language sql
stable
security definer
set search_path = ''
as $$
  select
    public.is_active()
      and coalesce(
        (select p.ai_suggestions_enabled
         from public.profiles p
         where p.user_id = auth.uid()),
        false),
    case
      when public.is_active() then
        (select p.ai_suggestions_changed_at
         from public.profiles p
         where p.user_id = auth.uid())
    end;
$$;

comment on function public.my_ai_suggestions() is
  'The signed-in person''s own AI-suggestions setting, and when they last changed it. Takes no arguments: who is asking comes from auth.uid() inside the body, so it can never be asked about somebody else. Always exactly one row, and enabled is false -- never null -- when there is no profile row, when the caller is suspended, and when nobody is signed in. security definer because no client role has SELECT on the two columns.';

-- WHO MAY CALL IT: authenticated, and nobody else -- the same three lines
-- 20261002122203_team_rules.sql and 20261004114313_suspend_accounts.sql use,
-- for the same reasons.
--
-- Postgres grants execute on a new function to PUBLIC automatically, and a
-- function in the public schema is published by PostgREST as an RPC endpoint,
-- so "PUBLIC" means anybody who can reach the API with the publishable key.
-- Revoking from PUBLIC closes that door before it is ever open.
--
-- anon is named separately, and here that is not belt-and-braces: Supabase
-- grants execute on new functions to anon BY NAME as well, which is a different
-- grant from the one PUBLIC holds, and revoking from PUBLIC does not remove it.
-- A signed-out caller would learn nothing -- auth.uid() is null, so is_active()
-- is false and the answer is false for everybody -- but this is a security
-- definer function reading columns nothing else may read, and the rule for that
-- kind of function is to grant the narrowest thing that works.
--
-- service_role is revoked too, and that IS a departure from the two files
-- above, where it keeps the grant Supabase made by name (see the note in
-- 20261004114313_suspend_accounts.sql, and issue #131). It is revoked here for
-- the same reason is_active() must never be called by a server function: an
-- admin-client connection has no signed-in user, so auth.uid() is null, so this
-- function would answer false for every caller and would do it without an
-- error. suggest-subtasks must read the column for a specific user id instead,
-- which is what the service_role select in section 4 is for. Taking the grant
-- away is the cheapest way to stop that mistake being made.
revoke execute on function public.my_ai_suggestions() from public;
revoke execute on function public.my_ai_suggestions() from anon;
revoke execute on function public.my_ai_suggestions() from service_role;
grant execute on function public.my_ai_suggestions() to authenticated;

-- ---------------------------------------------------------------------------
-- 4. Who may reach the two columns
-- ---------------------------------------------------------------------------
--
-- WHAT THE NEW COLUMNS GET BY DEFAULT, which is the reason this section exists.
-- Supabase grants select, insert, update and delete on every table in the
-- public schema to anon, authenticated and service_role -- its changelog of
-- 28 April 2026, "Breaking Change: Tables not exposed to Data and GraphQL API
-- automatically": "select, insert, update, and delete are granted to every
-- table in the `public` schema to the `anon`, `authenticated` and
-- `service_role` roles." Those are TABLE-level grants, and a table-level grant
-- covers every column the table ever grows. Read back from a sandbox built from
-- the eight migrations before this one, before any line below ran:
--
--   has_table_privilege('authenticated','public.profiles','SELECT')  -> t
--   has_table_privilege('authenticated','public.profiles','UPDATE')  -> t
--
-- So without the lines below both new columns arrive readable by every
-- non-suspended team mate through the existing select policy, and writable by
-- the person including the timestamp.
--
-- A COLUMN-LEVEL REVOKE WOULD DO NOTHING HERE, and that is the reason the shape
-- below looks heavy-handed. A table-level privilege cannot
-- have a column carved out of it: `revoke select (ai_suggestions_enabled) ...
-- from authenticated` removes a column-level grant, and there is none -- the
-- reach comes from the table-level grant, which stays, and the revoke succeeds
-- without a warning. The only way to express "every column except these two" is
-- to take the table-level privilege away and give back a column list. The same
-- move, for the same reason, as 20261006095847_invitation_status.sql -- whose
-- own evidence file records the finding with the output that establishes it:
-- evidence/build-it-18-invitation-status.md section 5, "REVOKE with no warning,
-- and the privilege is still there".
--
-- This is visible in the sandbox on a table that already has the shape:
--
--   has_table_privilege ('authenticated','public.invitations','INSERT')          -> f
--   has_column_privilege('authenticated','public.invitations','email','INSERT')  -> t
--   has_column_privilege('authenticated','public.invitations','status','INSERT') -> f
--
-- DELETE is deliberately untouched, for all three roles. It has no column level
-- to speak of, there is no delete policy on this table so nobody can delete a
-- profile through the app anyway, and nothing about this setting changes who may
-- remove a row.
--
-- SERVICE_ROLE IS IN THE WRITE HALF OF THIS, AND NOT IN THE READ HALF. Its
-- select is left alone -- suggest-subtasks has to read the setting -- but its
-- insert and update are narrowed with the other two roles, in section 4b. The
-- reason is issue #206's own sentence: "Nobody else can change it: not another
-- signed-in person, not a team owner, not a signed-out caller. The app's
-- operator can through the database." service_role is not the operator. It is
-- the role the three server functions connect as, and docs/plan.md says in as
-- many words that nobody switches this on anybody's behalf: "Not their team's
-- owner, not another member, not the owner of the app on their behalf."
revoke select, insert, update on table public.profiles from anon, authenticated;

-- Given straight back, column by column, for every column that existed before
-- this migration. The reach of anon and authenticated is therefore EXACTLY what
-- it was a moment ago, minus the two new columns -- which is the whole intended
-- change and nothing besides.
--
-- ANON IS RE-GRANTED, and it is worth saying why rather than leaving it to look
-- like carelessness. anon matches no policy on this table -- all four are `to
-- authenticated` -- so it reads and writes nothing today and will read and
-- write nothing after this. But privileges are checked BEFORE row-level
-- security, so the two are not interchangeable: with the privilege, a
-- signed-out select returns an empty result; without it, the same select
-- returns 42501. Nothing in the app reads this table signed out today, but
-- turning an empty answer into an error is a behaviour change, and "expand
-- only" means not making one.
--
-- A column added to this table by a later migration will not be in these lists
-- and will therefore be closed to both roles until a migration opens it. That
-- is the safer direction to fail in, and it is said here so the next person to
-- add a column knows it is waiting for them.
grant select (user_id, display_name, created_at)
  on table public.profiles to anon, authenticated;

grant insert (user_id, display_name, created_at)
  on table public.profiles to anon, authenticated;

grant update (user_id, display_name, created_at)
  on table public.profiles to anon, authenticated;

-- THE ONE NEW RIGHT THIS MIGRATION HANDS ANYBODY: the person may switch their
-- own setting. UPDATE on that one column, to authenticated only.
--
-- WHICH ROW is not this line's business and never could be: a privilege is
-- about a column, for a role, across the whole table. The row is decided by the
-- policy that is already there -- "You can change your own profile", using and
-- with check both (select auth.uid()) = user_id -- and by the restrictive
-- "Suspended accounts are refused everything" on top of it. So: the person,
-- their own row, not suspended. A team owner updating a member's row matches no
-- row and changes nothing; a signed-out caller is refused by this grant before
-- any policy is reached.
--
-- NOT anon: a signed-out caller has no setting to switch.
--
-- NOT insert, for either role, and that is the line that keeps "off for every
-- new row" true at the privilege layer as well as at the default. A profile row
-- created by the app can therefore never arrive already switched on.
--
--   ONE CONSEQUENCE WORTH KNOWING BEFORE THE SCREEN IS WRITTEN: a person with
--   no profile row cannot switch the setting on, because there is no row to
--   update and no insert that may name the column. They must save a nickname
--   first. That is not an artefact of this line -- display_name is not null with
--   no default, so a profile row cannot be created without one either way. The
--   screen in the next issue has to say so rather than appear to fail. An issue
--   is filed alongside this migration that says this.
--
-- NOT ai_suggestions_changed_at, for either role, which is the other half of
-- "never by the caller". The trigger in section 2 refuses a supplied value from
-- every caller; this grant means a client role cannot even name the column.
-- Together they are also what answers "nothing may let a caller switch the
-- setting on while writing some other column they are not allowed to write":
-- Postgres checks UPDATE column by column over the whole SET list, so a
-- statement setting both ai_suggestions_enabled and ai_suggestions_changed_at
-- is refused entire, and the setting does not move.
grant update (ai_suggestions_enabled) on table public.profiles to authenticated;

-- The server functions' role, named explicitly for the one column that will
-- need reading.
--
-- service_role still holds table-level select here -- the revoke above names
-- anon and authenticated only -- so this grants nothing it cannot already do
-- today. It is written down because issue #206 asks that any grant this
-- migration needs be written explicitly rather than rested on a default, and a
-- permission that exists only because of a default nobody wrote is a permission
-- nobody can see. docs/plan.md: suggest-subtasks "sends nothing to the AI
-- service unless the setting is on, and that is checked in the function".
grant select (ai_suggestions_enabled, ai_suggestions_changed_at)
  on table public.profiles to service_role;

-- ---------------------------------------------------------------------------
-- 4b. And no server function may switch the setting for anybody
-- ---------------------------------------------------------------------------
--
-- WHAT THIS CLOSES. Supabase's project default gives service_role table-level
-- insert and update on this table too, and a table-level grant covers every
-- column the table ever grows. So without these three lines a server function
-- could switch any person's setting on, for them, with no policy in the way --
-- service_role bypasses row-level security, so "You can change your own
-- profile" is never evaluated for it. Read back from the sandbox with the two
-- lines below removed:
--
--   set role service_role;
--   update public.profiles set ai_suggestions_enabled = true where user_id = <Carol>;
--   -> UPDATE 1, and the trigger duly stamped the time
--
-- That is the thing docs/plan.md forbids in the plainest words it has: "Only
-- that person can switch it, and only for themselves. Not their team's owner,
-- not another member, not the owner of the app on their behalf: there is no
-- screen on which anybody changes anybody else's."
--
-- NOTHING BREAKS, and that is checkable rather than hopeful: no server function
-- touches public.profiles at all today. `grep -rn profiles supabase/functions`
-- returns nothing, run on this commit. create-team, invite-member and
-- accept-invite write teams, team_members and invitations, and none of them has
-- ever read or written a profile.
--
-- Same move as the one in section 4, and for the same reason: the reach is
-- table-level, so a column-level revoke would succeed and remove
-- nothing. The three columns that existed before this migration are granted
-- straight back, so service_role's write reach is EXACTLY what it was a moment
-- ago, minus the two new columns.
--
-- SELECT AND DELETE ARE LEFT ALONE for service_role, unlike for the other two
-- roles: the select above is what suggest-subtasks needs, and nothing about
-- this setting changes who may remove a profile row.
--
-- IF A LATER FEATURE DOES WANT A SERVER FUNCTION TO WRITE THIS COLUMN, it grants
-- what it needs then, in its own migration, with a reason -- and it should
-- expect to update docs/plan.md's consent section first, because that section is
-- what these lines are enforcing.
revoke insert, update on table public.profiles from service_role;

grant insert (user_id, display_name, created_at)
  on table public.profiles to service_role;

grant update (user_id, display_name, created_at)
  on table public.profiles to service_role;

-- ---------------------------------------------------------------------------
-- 5. The 30 October 2026 change, and why this migration is unaffected
-- ---------------------------------------------------------------------------
--
-- Supabase applies "new public tables are not exposed by default" to existing
-- projects on 30 October 2026 (changelog 45329), and issue #130 holds that
-- question for this repository.
--
-- THIS MIGRATION ADDS COLUMNS, NOT A TABLE. #130's own sandbox settled what the
-- change is: it alters DEFAULT privileges, so "the old table keeps its grants,
-- the new one has none". public.profiles already exists and this migration
-- creates no table, so nothing here depends on what a table created after that
-- date would be granted.
--
-- AND IT IS THE DATE-PROOF DIRECTION ANYWAY, which is the better reason not to
-- worry about it: every right this migration relies on is now written down in
-- sections 4 and 4b by name -- the three re-granted columns for anon,
-- authenticated and service_role, the one update for authenticated, the two
-- selects for service_role, and the execute for authenticated on
-- my_ai_suggestions(). An explicit grant is not a default and is not withdrawn
-- by a change to defaults.
--
-- The one right this file still rests on a default for is service_role's
-- TABLE-level select, which is why the column-level select above is written out
-- as well: if that default is ever withdrawn, suggest-subtasks keeps the one
-- read it actually needs. Nothing else here depends on a default: every other
-- privilege on this table has now been either revoked by name or granted by
-- name.
